// Typography + layout systems for the Slides/Carousel generator.
// Each preset is a self-contained visual language: font stack, weight,
// alignment, case, and overlay treatment. Designed to feel distinct the
// moment you switch between them.

export type SlideAspect = '1:1' | '4:5' | '9:16' | '16:9' | 'original';

export const ASPECT_RATIOS: Record<SlideAspect, { label: string; w: number; h: number; blurb: string }> = {
  '1:1': { label: 'Feed square', w: 1080, h: 1080, blurb: 'Instagram · LinkedIn feed' },
  '4:5': { label: 'Portrait feed', w: 1080, h: 1350, blurb: 'Instagram portrait · Pinterest' },
  '9:16': { label: 'Story / Reel', w: 1080, h: 1920, blurb: 'Stories · Reels · TikTok · Shorts' },
  '16:9': { label: 'Landscape', w: 1920, h: 1080, blurb: 'LinkedIn · X · YouTube Shorts cover' },
  'original': { label: 'Original', w: 0, h: 0, blurb: 'Native resolution — no resize · print-ready' },
};

export type OverlayMode =
  | 'solid-bottom'   // opaque block pinned to the bottom third
  | 'gradient'       // top-to-bottom darkening gradient
  | 'framed'         // thin outlined rectangle containing text
  | 'split'          // image left / text panel right (or bottom for portrait)
  | 'full-bleed'     // text on image, no overlay treatment
  | 'vignette'       // radial darken at the edges
  | 'marquee';       // horizontal stripe across the middle

export type Alignment = 'start' | 'center' | 'end';

export interface SlidePreset {
  id: string;
  label: string;          // capslock in UI
  blurb: string;          // one-line human description
  accent: string;         // default accent hex
  titleFontVar: string;   // css var() reference
  bodyFontVar: string;
  titleWeight: number;
  bodyWeight: number;
  titleCase: 'upper' | 'lower' | 'normal';
  bodyCase: 'upper' | 'lower' | 'normal';
  titleTracking: string;  // e.g. '-0.02em'
  bodyTracking: string;
  align: Alignment;
  overlay: OverlayMode;
  surface: string;        // overlay colour — hex or rgba
  ink: string;            // text colour
  imageFilter?: string;   // optional CSS filter for image
  titleSize: number;      // relative to a 1080-wide canvas
  bodySize: number;
  leadingTitle: number;   // line-height
  leadingBody: number;
  maxTitleChars: number;  // agent contract: cap title length for this preset
  maxBodyChars: number;
}

export const SLIDE_PRESETS: SlidePreset[] = [
  {
    id: 'editorial',
    label: 'EDITORIAL',
    blurb: 'Classic magazine serif · quiet confidence',
    accent: '#ffb72a',
    titleFontVar: 'var(--font-playfair)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 900,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.015em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'gradient',
    surface: 'rgba(0,0,0,0.55)',
    ink: '#ffffff',
    titleSize: 92,
    bodySize: 26,
    leadingTitle: 1.02,
    leadingBody: 1.4,
    maxTitleChars: 60,
    maxBodyChars: 140,
  },
  {
    id: 'swiss',
    label: 'SWISS',
    blurb: 'Grid · Space Grotesk · zero ornament',
    accent: '#000000',
    titleFontVar: 'var(--font-space-grotesk)',
    bodyFontVar: 'var(--font-space-grotesk)',
    titleWeight: 700,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.035em',
    bodyTracking: '-0.01em',
    align: 'start',
    overlay: 'framed',
    surface: '#ffffff',
    ink: '#000000',
    titleSize: 78,
    bodySize: 24,
    leadingTitle: 0.95,
    leadingBody: 1.35,
    maxTitleChars: 48,
    maxBodyChars: 120,
  },
  {
    id: 'brutal',
    label: 'BRUTAL',
    blurb: 'Heavy caps · no mercy',
    accent: '#ccff00',
    titleFontVar: 'var(--font-archivo-black)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 400,
    bodyWeight: 500,
    titleCase: 'upper',
    bodyCase: 'upper',
    titleTracking: '-0.04em',
    bodyTracking: '0.08em',
    align: 'start',
    overlay: 'solid-bottom',
    surface: '#000000',
    ink: '#ccff00',
    titleSize: 112,
    bodySize: 18,
    leadingTitle: 0.9,
    leadingBody: 1.5,
    maxTitleChars: 40,
    maxBodyChars: 80,
  },
  {
    id: 'manifesto',
    label: 'MANIFESTO',
    blurb: 'Fraunces display · oversized pull-quote',
    accent: '#ff3d3d',
    titleFontVar: 'var(--font-fraunces)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 900,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.03em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'vignette',
    surface: 'rgba(0,0,0,0.6)',
    ink: '#f4ecd8',
    titleSize: 128,
    bodySize: 28,
    leadingTitle: 0.92,
    leadingBody: 1.4,
    maxTitleChars: 40,
    maxBodyChars: 110,
  },
  {
    id: 'quiet',
    label: 'QUIET',
    blurb: 'Instrument Serif · lots of space',
    accent: '#8ab4ff',
    titleFontVar: 'var(--font-instrument-serif)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 400,
    bodyWeight: 300,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.01em',
    bodyTracking: '0.01em',
    align: 'center',
    overlay: 'full-bleed',
    surface: 'transparent',
    ink: '#ffffff',
    titleSize: 86,
    bodySize: 22,
    leadingTitle: 1.05,
    leadingBody: 1.55,
    maxTitleChars: 52,
    maxBodyChars: 130,
    imageFilter: 'brightness(0.65) saturate(1.1)',
  },
  {
    id: 'zine',
    label: 'ZINE',
    blurb: 'Bricolage · stacked weights · indie',
    accent: '#ff6fb5',
    titleFontVar: 'var(--font-bricolage)',
    bodyFontVar: 'var(--font-bricolage)',
    titleWeight: 800,
    bodyWeight: 500,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.04em',
    bodyTracking: '-0.01em',
    align: 'start',
    overlay: 'marquee',
    surface: '#ff6fb5',
    ink: '#000000',
    titleSize: 96,
    bodySize: 22,
    leadingTitle: 0.95,
    leadingBody: 1.4,
    maxTitleChars: 48,
    maxBodyChars: 110,
  },
  {
    id: 'terminal',
    label: 'TERMINAL',
    blurb: 'DM Mono · command-line hacker',
    accent: '#00ff88',
    titleFontVar: 'var(--font-dm-mono)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 500,
    bodyWeight: 400,
    titleCase: 'lower',
    bodyCase: 'lower',
    titleTracking: '0',
    bodyTracking: '0',
    align: 'start',
    overlay: 'framed',
    surface: 'rgba(5,10,5,0.85)',
    ink: '#00ff88',
    titleSize: 60,
    bodySize: 18,
    leadingTitle: 1.1,
    leadingBody: 1.5,
    maxTitleChars: 72,
    maxBodyChars: 160,
    imageFilter: 'grayscale(0.6) contrast(1.1)',
  },
  {
    id: 'hype',
    label: 'HYPE',
    blurb: 'Syne scale-pop · sports launch energy',
    accent: '#ffd43a',
    titleFontVar: 'var(--font-syne)',
    bodyFontVar: 'var(--font-space-grotesk)',
    titleWeight: 800,
    bodyWeight: 500,
    titleCase: 'upper',
    bodyCase: 'upper',
    titleTracking: '-0.03em',
    bodyTracking: '0.15em',
    align: 'center',
    overlay: 'vignette',
    surface: 'rgba(0,0,0,0.35)',
    ink: '#ffffff',
    titleSize: 140,
    bodySize: 20,
    leadingTitle: 0.88,
    leadingBody: 1.3,
    maxTitleChars: 24,
    maxBodyChars: 70,
  },
  {
    id: 'split',
    label: 'SPLIT',
    blurb: 'Half image · half type · LinkedIn slides',
    accent: '#3b82f6',
    titleFontVar: 'var(--font-space-grotesk)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 700,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.03em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'split',
    surface: '#0a0a0a',
    ink: '#ffffff',
    titleSize: 72,
    bodySize: 22,
    leadingTitle: 1.0,
    leadingBody: 1.45,
    maxTitleChars: 60,
    maxBodyChars: 220,
  },
  {
    id: 'neo-retro',
    label: 'NEO-RETRO',
    blurb: 'Chrome gradient · 80s VHS',
    accent: '#ff6fb5',
    titleFontVar: 'var(--font-syne)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 800,
    bodyWeight: 400,
    titleCase: 'upper',
    bodyCase: 'upper',
    titleTracking: '-0.02em',
    bodyTracking: '0.12em',
    align: 'center',
    overlay: 'gradient',
    surface: 'linear-gradient(180deg, rgba(255,111,181,0.35) 0%, rgba(0,0,0,0.7) 100%)',
    ink: '#ffffff',
    titleSize: 110,
    bodySize: 18,
    leadingTitle: 0.92,
    leadingBody: 1.4,
    maxTitleChars: 28,
    maxBodyChars: 80,
    imageFilter: 'saturate(1.2) contrast(1.05)',
  },
  {
    id: 'y2k',
    label: 'Y2K',
    blurb: 'Vibrant futuristic · Syne + DM Mono',
    accent: '#00f0ff',
    titleFontVar: 'var(--font-syne)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 800,
    bodyWeight: 500,
    titleCase: 'upper',
    bodyCase: 'normal',
    titleTracking: '0.05em',
    bodyTracking: '0',
    align: 'center',
    overlay: 'framed',
    surface: 'rgba(0, 240, 255, 0.15)',
    ink: '#ffffff',
    titleSize: 100,
    bodySize: 22,
    leadingTitle: 0.9,
    leadingBody: 1.5,
    maxTitleChars: 36,
    maxBodyChars: 100,
    imageFilter: 'contrast(1.2) saturate(1.5)',
  },
  {
    id: 'acid',
    label: 'ACID',
    blurb: 'High contrast · Bricolage Grotesque',
    accent: '#ccff00',
    titleFontVar: 'var(--font-bricolage)',
    bodyFontVar: 'var(--font-space-grotesk)',
    titleWeight: 800,
    bodyWeight: 600,
    titleCase: 'upper',
    bodyCase: 'lower',
    titleTracking: '-0.04em',
    bodyTracking: '-0.02em',
    align: 'start',
    overlay: 'solid-bottom',
    surface: '#000000',
    ink: '#ccff00',
    titleSize: 130,
    bodySize: 26,
    leadingTitle: 0.85,
    leadingBody: 1.3,
    maxTitleChars: 30,
    maxBodyChars: 90,
  },
  {
    id: 'bauhaus',
    label: 'BAUHAUS',
    blurb: 'Pure geometry · Archivo Black',
    accent: '#ff2a2a',
    titleFontVar: 'var(--font-archivo-black)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 400,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.02em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'split',
    surface: '#f4f4f4',
    ink: '#0a0a0a',
    titleSize: 96,
    bodySize: 24,
    leadingTitle: 0.95,
    leadingBody: 1.4,
    maxTitleChars: 45,
    maxBodyChars: 180,
  },
  {
    id: 'glass',
    label: 'GLASSMORPH',
    blurb: 'Ethereal · Space Grotesk',
    accent: '#ffffff',
    titleFontVar: 'var(--font-space-grotesk)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 700,
    bodyWeight: 300,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.03em',
    bodyTracking: '0.02em',
    align: 'center',
    overlay: 'full-bleed',
    surface: 'transparent',
    ink: '#ffffff',
    titleSize: 84,
    bodySize: 24,
    leadingTitle: 1.1,
    leadingBody: 1.6,
    maxTitleChars: 50,
    maxBodyChars: 140,
    imageFilter: 'blur(2px) brightness(0.8)',
  },
  {
    id: 'minimalist',
    label: 'MINIMALIST',
    blurb: 'Ultra clean · tiny text · whitespace',
    accent: '#000000',
    titleFontVar: 'var(--font-dm-sans)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 400,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.02em',
    bodyTracking: '0.02em',
    align: 'start',
    overlay: 'solid-bottom',
    surface: '#ffffff',
    ink: '#000000',
    titleSize: 64,
    bodySize: 16,
    leadingTitle: 1.1,
    leadingBody: 1.6,
    maxTitleChars: 80,
    maxBodyChars: 160,
  },
  {
    id: 'cyberpunk',
    label: 'CYBERPUNK',
    blurb: 'Neon glitch · Syne + DM Mono',
    accent: '#ff003c',
    titleFontVar: 'var(--font-syne)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 800,
    bodyWeight: 400,
    titleCase: 'upper',
    bodyCase: 'lower',
    titleTracking: '0.02em',
    bodyTracking: '0.05em',
    align: 'end',
    overlay: 'vignette',
    surface: 'rgba(0, 5, 20, 0.7)',
    ink: '#00ffcc',
    titleSize: 110,
    bodySize: 20,
    leadingTitle: 0.9,
    leadingBody: 1.4,
    maxTitleChars: 40,
    maxBodyChars: 100,
    imageFilter: 'hue-rotate(300deg) contrast(1.3) saturate(1.4)',
  },
  {
    id: 'vaporwave',
    label: 'VAPORWAVE',
    blurb: 'Aesthetic retro · Playfair + sans',
    accent: '#00ffff',
    titleFontVar: 'var(--font-playfair)',
    bodyFontVar: 'var(--font-space-grotesk)',
    titleWeight: 600,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'upper',
    titleTracking: '0.05em',
    bodyTracking: '0.2em',
    align: 'center',
    overlay: 'gradient',
    surface: 'linear-gradient(180deg, rgba(255,113,206,0.2) 0%, rgba(1,205,254,0.6) 100%)',
    ink: '#ffffff',
    titleSize: 96,
    bodySize: 16,
    leadingTitle: 1.0,
    leadingBody: 1.6,
    maxTitleChars: 50,
    maxBodyChars: 90,
  },
  {
    id: 'noir',
    label: 'NOIR',
    blurb: 'Cinema grain · Fraunces · stark',
    accent: '#ffffff',
    titleFontVar: 'var(--font-fraunces)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 700,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'upper',
    titleTracking: '-0.02em',
    bodyTracking: '0.25em',
    align: 'center',
    overlay: 'vignette',
    surface: 'rgba(0,0,0,0.7)',
    ink: '#ffffff',
    titleSize: 104,
    bodySize: 14,
    leadingTitle: 1.0,
    leadingBody: 1.8,
    maxTitleChars: 48,
    maxBodyChars: 100,
    imageFilter: 'grayscale(1) contrast(1.15)',
  },
  {
    id: 'polaroid',
    label: 'POLAROID',
    blurb: 'Memory border · handwriting feel',
    accent: '#ffb72a',
    titleFontVar: 'var(--font-instrument-serif)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 400,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.01em',
    bodyTracking: '0.02em',
    align: 'center',
    overlay: 'framed',
    surface: '#fafaf5',
    ink: '#1a1a1a',
    titleSize: 60,
    bodySize: 20,
    leadingTitle: 1.1,
    leadingBody: 1.5,
    maxTitleChars: 60,
    maxBodyChars: 120,
    imageFilter: 'sepia(0.2) contrast(0.95) brightness(1.05)',
  },
  {
    id: 'zen',
    label: 'ZEN',
    blurb: 'Wabi-sabi · silence · one line',
    accent: '#c7b8a1',
    titleFontVar: 'var(--font-instrument-serif)',
    bodyFontVar: 'var(--font-instrument-serif)',
    titleWeight: 400,
    bodyWeight: 400,
    titleCase: 'lower',
    bodyCase: 'lower',
    titleTracking: '-0.01em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'full-bleed',
    surface: 'transparent',
    ink: '#f4f0e8',
    titleSize: 72,
    bodySize: 22,
    leadingTitle: 1.2,
    leadingBody: 1.6,
    maxTitleChars: 40,
    maxBodyChars: 80,
    imageFilter: 'brightness(0.75) saturate(0.85)',
  },
  {
    id: 'gradient',
    label: 'GRADIENT',
    blurb: 'Mesh colour wash · Syne display',
    accent: '#a855f7',
    titleFontVar: 'var(--font-syne)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 800,
    bodyWeight: 400,
    titleCase: 'normal',
    bodyCase: 'normal',
    titleTracking: '-0.035em',
    bodyTracking: '0.01em',
    align: 'start',
    overlay: 'gradient',
    surface: 'linear-gradient(135deg, rgba(168,85,247,0.7) 0%, rgba(59,130,246,0.5) 50%, rgba(236,72,153,0.7) 100%)',
    ink: '#ffffff',
    titleSize: 92,
    bodySize: 22,
    leadingTitle: 0.98,
    leadingBody: 1.5,
    maxTitleChars: 55,
    maxBodyChars: 140,
  },
  {
    id: 'tabloid',
    label: 'TABLOID',
    blurb: 'News ticker · condensed caps',
    accent: '#ff3d3d',
    titleFontVar: 'var(--font-archivo-black)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 400,
    bodyWeight: 500,
    titleCase: 'upper',
    bodyCase: 'upper',
    titleTracking: '-0.03em',
    bodyTracking: '0.1em',
    align: 'start',
    overlay: 'marquee',
    surface: '#ff3d3d',
    ink: '#ffffff',
    titleSize: 120,
    bodySize: 18,
    leadingTitle: 0.88,
    leadingBody: 1.4,
    maxTitleChars: 35,
    maxBodyChars: 80,
  },
  {
    id: 'duotone',
    label: 'DUOTONE',
    blurb: 'Two-colour wash · bold sans',
    accent: '#ff6fb5',
    titleFontVar: 'var(--font-space-grotesk)',
    bodyFontVar: 'var(--font-dm-sans)',
    titleWeight: 700,
    bodyWeight: 400,
    titleCase: 'upper',
    bodyCase: 'normal',
    titleTracking: '-0.03em',
    bodyTracking: '0',
    align: 'start',
    overlay: 'full-bleed',
    surface: 'transparent',
    ink: '#ffffff',
    titleSize: 92,
    bodySize: 22,
    leadingTitle: 0.95,
    leadingBody: 1.45,
    maxTitleChars: 48,
    maxBodyChars: 120,
    imageFilter: 'grayscale(1) contrast(1.2) sepia(0.3) hue-rotate(260deg) saturate(3)',
  },
  {
    id: 'risograph',
    label: 'RISOGRAPH',
    blurb: 'Offset print · screenprint halftone',
    accent: '#2e6cff',
    titleFontVar: 'var(--font-bricolage)',
    bodyFontVar: 'var(--font-dm-mono)',
    titleWeight: 800,
    bodyWeight: 500,
    titleCase: 'normal',
    bodyCase: 'upper',
    titleTracking: '-0.03em',
    bodyTracking: '0.1em',
    align: 'start',
    overlay: 'solid-bottom',
    surface: '#fff6e0',
    ink: '#1a1a1a',
    titleSize: 90,
    bodySize: 16,
    leadingTitle: 0.95,
    leadingBody: 1.4,
    maxTitleChars: 48,
    maxBodyChars: 120,
    imageFilter: 'contrast(1.1) saturate(1.3) hue-rotate(5deg)',
  }
];

export function getPreset(id: string): SlidePreset {
  return SLIDE_PRESETS.find((p) => p.id === id) ?? SLIDE_PRESETS[0];
}
