import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const AlpineArchitects: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={75}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "OPEN SPACE",
          "kicker": "where the view begins",
          "accent": "#a9a9a9",
          "transition": "fade"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "UNBOUND LUXE",
          "kicker": "dramatic light, endless horizon",
          "accent": "#4A6B7A",
          "transition": "slide-right"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "EPIC SCALE",
          "kicker": "architecture meets the wild",
          "accent": "#A9B3B7",
          "transition": "flip"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "PERFECT VIEW",
          "kicker": "the ultimate escape",
          "accent": "#4a6a53",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
