import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const AlpineDream: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={195}
      transitionLengthInFrames={24}
      scenes={[
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "The quiet architecture of belonging.",
          "kicker": "where the wild mountains meet the stillness of your soul.",
          "accent": "#b0a090"
        },
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "Finding clarity in the white expanse.",
          "kicker": "a moment suspended between the cold and the calm.",
          "accent": "#A0A090",
          "transition": "fade"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "The embrace of natural light.",
          "kicker": "letting the curve of the world redefine your view.",
          "accent": "#a0c4b2",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "Witnessing the grandeur of time.",
          "kicker": "some views are meant to slow your breath and change your perspective.",
          "accent": "#b0c4de",
          "transition": "fade"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Where the horizon whispers secrets.",
          "kicker": "and the only thing that matters is the view.",
          "accent": "#1A435B",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
