import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const AlpineSanctuary: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={272}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "ARCHITECTURAL PERFECTION",
          "kicker": "Where minimalist design meets the majesty of the alpine view. A new standard in living.",
          "accent": "#4a90e2",
          "transition": "slide-right"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "THE VIEW IS THE FEATURE",
          "kicker": "Experience the dramatic contrast of nature and curated luxury. Every angle, a masterpiece.",
          "accent": "#303f9f",
          "transition": "flip"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "COMFORT. REIMAGINED.",
          "kicker": "Seamless integration of modern comfort and breathtaking natural elements. Designed for life.",
          "accent": "#00bcd4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "BEYOND EXPECTATION",
          "kicker": "Panoramic living that redefines the boundary between indoor sanctuary and wild frontier.",
          "accent": "#4fc3f7",
          "transition": "wipe"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "YOUR NEXT HORIZON",
          "kicker": "Discover the pinnacle of modern mountain living. Link in bio for exclusive access.",
          "accent": "#673ab7",
          "transition": "slide-right"
        }
      ]}
    />
  );
};
