import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const ApexPredator: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      theme={"magazine"}
      motionFeel={"bouncy"}
      transitionEnergy={"medium"}
      gradePreset={"warm_cinematic"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/93f20b5b1d.png",
          "caption": "THE WILD IS UNCOMPROMISING.",
          "kicker": "A black bear moves through the alpine meadow, showing no hesitation.",
          "accent": "#8c9a7e",
          "transition": "flash-cut",
          "narration": "The wild is uncompromising. A black bear moves through the alpine meadow, showing no hesitation.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/2096c202a2.png",
          "caption": "WATCHFUL. UNTAMEABLE.",
          "kicker": "The dense foliage hides a powerful presence waiting in the green.",
          "accent": "#6b8e23",
          "transition": "slide-left",
          "narration": "Watchful. Untameable. The dense foliage hides a powerful presence waiting in the green.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/020b874f25.png",
          "caption": "PRIMAL POWER. NO FILTER.",
          "kicker": "The panther dominates the mountainous view with silent authority.",
          "accent": "#5c6b5b",
          "transition": "flip",
          "narration": "Primal power. No filter. The panther dominates the mountainous view with silent authority.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/cc4e7cd32b.png",
          "caption": "THE GAZE. THE STARE.",
          "kicker": "panther center-left, mountains filling background",
          "accent": "#7a839b",
          "transition": "wipe-right",
          "narration": "A black panther is positioned in the foreground, looking directly at the camera against a hazy mountain backdrop. panther center-left, mountains filling background",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/9f23ef5d69.png",
          "caption": "RAW AUTHENTICITY.",
          "kicker": "A moment of quiet observation captured in the wild setting.",
          "accent": "#333333",
          "transition": "fade",
          "narration": "Raw authenticity. A moment of quiet observation captured in the wild setting.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/f582a0440d.png",
          "caption": "STEALTH IS THE LANGUAGE.",
          "kicker": "Moving through the tall, dry grass, barely visible.",
          "accent": "#555555",
          "transition": "slide-right",
          "narration": "Stealth is the language. Moving through the tall, dry grass, barely visible.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/88de89ba18.png",
          "caption": "THE UNBLINKING GAZE.",
          "kicker": "An intense portrait showing the panther's unwavering focus.",
          "accent": "#333333",
          "transition": "chromatic-split",
          "narration": "The unblinking gaze. An intense portrait showing the panther's unwavering focus.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/0d3fbc9cfc.png",
          "caption": "EMERGING. UNSTOPPABLE.",
          "kicker": "The final reveal from the tall grass into the open valley.",
          "accent": "#5d6d7e",
          "narration": "Emerging. Unstoppable. The final reveal from the tall grass into the open valley.",
          "textPlacement": "bottom-left"
        }
      ]}
      sceneTTSPaths={["tts/ApexPredator-scene-0.wav","tts/ApexPredator-scene-1.wav","tts/ApexPredator-scene-2.wav","tts/ApexPredator-scene-3.wav","tts/ApexPredator-scene-4.wav","tts/ApexPredator-scene-5.wav","tts/ApexPredator-scene-6.wav","tts/ApexPredator-scene-7.wav"]}
    />
  );
};
