import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const ArchitecturalDreamscape: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={351}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "Opulence Meets Tomorrow",
          "kicker": "where timeless design meets the edge of possibility. a study in curated luxury.",
          "accent": "#a78bfa",
          "transition": "fade",
          "narration": "Observe the seamless integration of form and function in this breathtaking space."
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Symmetry in Structure",
          "kicker": "the careful balance of light, material, and negative space defines modern grandeur.",
          "accent": "#ffd43a",
          "transition": "slide-bottom",
          "narration": "Every line, every curve, speaks to a philosophy of refined, enduring beauty."
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "Material Storytelling",
          "kicker": "the interplay of polished stone and brushed metal creates a tactile narrative for the inhabitant.",
          "accent": "#4cc9ff",
          "transition": "slide-right",
          "narration": "It is not just a room; it is a gallery for the art of living."
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "Illuminated Pathways",
          "kicker": "the strategic placement of light sources guides the eye through moments of quiet contemplation.",
          "accent": "#ffb72a",
          "transition": "fade",
          "narration": "Notice how the ambient lighting sculpts the architecture, revealing hidden depths."
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "Zen of the Void",
          "kicker": "finding absolute calm within a setting of immense, controlled drama.",
          "accent": "#a78bfa",
          "transition": "slide-left",
          "narration": "Here, the noise of the outside world dissolves into perfect, quiet composition."
        },
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "Curated Living Space",
          "kicker": "a masterclass in minimalist opulence, where every object feels intentional and necessary.",
          "accent": "#a78bfa",
          "transition": "wipe-bottom",
          "narration": "The design speaks of quiet confidence—a space built for thoughtful existence."
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Geometric Harmony",
          "kicker": "the repeating patterns and clean lines anchor the entire composition in perfect order.",
          "accent": "#ffd43a",
          "transition": "iris",
          "narration": "The underlying geometry provides a sense of unwavering stability and grace."
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "Sculpted by Light",
          "kicker": "the way natural light interacts with these surfaces creates living, breathing art throughout the day.",
          "accent": "#4cc9ff",
          "transition": "fade",
          "narration": "Watch how the shadows shift, transforming the mood from morning crispness to evening warmth."
        }
      ]}
      sceneTTSPaths={["tts/ArchitecturalDreamscape-scene-0.wav","tts/ArchitecturalDreamscape-scene-1.wav","tts/ArchitecturalDreamscape-scene-2.wav","tts/ArchitecturalDreamscape-scene-3.wav","tts/ArchitecturalDreamscape-scene-4.wav","tts/ArchitecturalDreamscape-scene-5.wav","tts/ArchitecturalDreamscape-scene-6.wav","tts/ArchitecturalDreamscape-scene-7.wav"]}
    />
  );
};
