import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const ArchitecturalNarrative: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-playfair), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"minimal"}
      sceneLengthInFrames={205}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/35244de977.png",
          "caption": "Defining Space Through Structure",
          "kicker": "The interplay of raw concrete and natural wood defines modern luxury living.",
          "accent": "#2e4c63",
          "transition": "fade",
          "narration": "We begin by examining how structure dictates the flow of light and life within these expansive modern sanctuaries."
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "Zen Minimalism Meets Grand Scale",
          "kicker": "A sanctuary where deep teal seating anchors the view of the snowy peaks.",
          "accent": "#2e4c63",
          "transition": "slide-right",
          "narration": "The design philosophy here is one of controlled emptiness, allowing the landscape to become the primary artwork."
        },
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "Teal Hues, Natural Wood Grain",
          "kicker": "Balancing opulent comfort with the stark, beautiful geometry of the mountain backdrop.",
          "accent": "#466e7b",
          "transition": "flip",
          "narration": "Notice the material palette: deep, saturated teals juxtaposed against warm, raw wood accents."
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Moody Depth, Elevated Comfort",
          "kicker": "Sophisticated design utilizes rich tones to frame the dramatic, moody mountain vista.",
          "accent": "#3b5c6b",
          "transition": "slide-left",
          "narration": "The mood shifts here, embracing a more dramatic, moody atmosphere that complements the rugged exterior."
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "Bright Light, Cozy Geometry",
          "kicker": "Natural light floods the space, highlighting the interplay between mustard tones and cool stone.",
          "accent": "#c49954",
          "transition": "wipe-right",
          "narration": "This space captures the perfect balance: bright, airy, yet grounded by rich, earthy tones."
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "The View as Primary Element",
          "kicker": "Architectural design must always defer to the natural spectacle outside the frame.",
          "accent": "#a08c74",
          "transition": "slide-bottom",
          "narration": "Ultimately, the best interior design doesn't compete with the view; it frames it."
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "Sanctuary of Scale",
          "kicker": "A masterclass in negative space, letting the mountain panorama dominate the composition.",
          "accent": "#2e4c63",
          "transition": "fade",
          "narration": "It is the scale, the sheer, uninterrupted scale, that defines this high-end modern mountain sanctuary."
        }
      ]}
      sceneTTSPaths={["tts/ArchitecturalNarrative-scene-0.wav","tts/ArchitecturalNarrative-scene-1.wav","tts/ArchitecturalNarrative-scene-2.wav","tts/ArchitecturalNarrative-scene-3.wav","tts/ArchitecturalNarrative-scene-4.wav","tts/ArchitecturalNarrative-scene-5.wav","tts/ArchitecturalNarrative-scene-6.wav"]}
    />
  );
};
