import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const AttitudeCheck: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"minimal"}
      sceneLengthInFrames={100}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/91933ae417.png",
          "caption": "YOU ARE NOT SAFE.",
          "kicker": "the clown doll just knows too much. stay out of his lane.",
          "accent": "#cc0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "VIBES ARE EVERYTHING.",
          "kicker": "pink hair, pink attitude. the glow up is permanent.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "MYSTERY IS MY POWER.",
          "kicker": "smoke and silence. the look that says you won't talk about it.",
          "accent": "#333333",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "SMOKE & GRIT.",
          "kicker": "the smoke clears, but the attitude remains. raw and unfiltered.",
          "accent": "#d45100",
          "transition": "slide-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE STARE.",
          "kicker": "you can't read him, but you can feel the heat. pure swagger.",
          "accent": "#a08c4e",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "NOCTURNAL GLOW.",
          "kicker": "the city lights and the smoke. a perfect, effortless moment.",
          "accent": "#B8860B",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "INTENSITY LEVEL: MAX.",
          "kicker": "the red face, the smoke, the moment. pure, unfiltered drama.",
          "accent": "#cc3300",
          "transition": "flip"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "UNBOTHERED.",
          "kicker": "the Muppet energy, the cool smoke. nobody asked for this level of chill.",
          "accent": "#006666",
          "transition": "slide-right"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLOW UP IS REAL.",
          "kicker": "it's not just the smoke, it's the confidence. the mystery deepens.",
          "accent": "#A0522D",
          "transition": "slide-left"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "DON'T LOOK BACK.",
          "kicker": "the journey is gritty, the attitude is permanent. keep moving.",
          "accent": "#333333",
          "transition": "wipe"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "WARNING: DO NOT PROVOKE.",
          "kicker": "the clown doll is watching. you know what happens next.",
          "accent": "#cc0000",
          "transition": "slide-top"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THE VIBE CHECK.",
          "kicker": "this is the soundtrack to your best, most reckless nights.",
          "accent": "#0077be",
          "transition": "flip"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE PAYOFF.",
          "kicker": "sultry, cool, and completely untouchable. the perfect exit shot.",
          "accent": "#AAAAAA",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "OWN THE MOMENT.",
          "kicker": "the look that shuts down the conversation. pure, unadulterated swagger.",
          "accent": "#c2b280",
          "transition": "slide-right"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE ENDGAME.",
          "kicker": "it all comes back to the smoke and the silence. the ultimate mystery.",
          "accent": "#333333",
          "transition": "wipe"
        }
      ]}
    />
  );
};
