import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const ConcreteHorizon: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={38}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/9dc402e750.png",
          "caption": "VOID",
          "kicker": "structure meets the wild",
          "accent": "#b0c4de",
          "transition": "wipe"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "ASCEND",
          "kicker": "the peak of the design",
          "accent": "#556b2f",
          "transition": "slide-right"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "LIMITLESS",
          "kicker": "geometry and the horizon",
          "accent": "#6b7a6c",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
