import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const DollhouseDread: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      gradePreset={"warm_cinematic"}
      sceneLengthInFrames={144}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POV: The vibe check failed",
          "kicker": "When the facade cracks and you see the real edit.",
          "accent": "#ff3d3d",
          "transition": "fade",
          "narration": "POV: The vibe check failed. When the facade cracks and you see the real edit."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "It's giving toxic archive",
          "kicker": "Understated drama, no cap. This silhouette hits different.",
          "accent": "#ff8a2a",
          "transition": "slide-right",
          "narration": "It's giving toxic archive. Understated drama, no cap. This silhouette hits different."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "Nobody talks about",
          "kicker": "The quiet luxury of being perpetually annoyed.",
          "accent": "#a78bfa",
          "transition": "flip",
          "narration": "Nobody talks about the quiet luxury of being perpetually annoyed."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "Proportion check: Failed",
          "kicker": "The drape is everything. A masterclass in controlled chaos.",
          "accent": "#ff3d3d",
          "transition": "slide-bottom",
          "narration": "Proportion check: Failed. The drape is everything. A masterclass in controlled chaos."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "This is your sign to",
          "kicker": "Embrace the raw, unedited moment. Don't polish the edges.",
          "accent": "#ffb72a",
          "transition": "wipe-right",
          "narration": "This is your sign to embrace the raw, unedited moment. Don't polish the edges."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "Lowkey, the main character",
          "kicker": "When the mood is 'over it' but the fit is perfect.",
          "accent": "#180808",
          "transition": "slide-left",
          "narration": "Lowkey, the main character. When the mood is 'over it' but the fit is perfect."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "The final edit.",
          "kicker": "It's giving 'I've seen it all' energy. Save this mood board.",
          "accent": "#ff3d3d",
          "transition": "fade",
          "narration": "The final edit. It's giving 'I've seen it all' energy. Save this mood board."
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "Understand the assignment.",
          "kicker": "The ultimate power move: looking bored while wearing couture.",
          "accent": "#080808",
          "transition": "wipe-bottom",
          "narration": "Understand the assignment. The ultimate power move: looking bored while wearing couture."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "The silhouette speaks.",
          "kicker": "Effortless proportions that require zero explanation.",
          "accent": "#ff3d3d",
          "transition": "iris",
          "narration": "The silhouette speaks. Effortless proportions that require zero explanation."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "Archive deep cut.",
          "kicker": "This level of drama is unmatched. Follow for pt 2.",
          "accent": "#ff8a2a",
          "transition": "slide-right",
          "narration": "Archive deep cut. This level of drama is unmatched. Follow for pt 2."
        }
      ]}
      sceneTTSPaths={["tts/DollhouseDread-scene-0.wav","tts/DollhouseDread-scene-1.wav","tts/DollhouseDread-scene-2.wav","tts/DollhouseDread-scene-3.wav","tts/DollhouseDread-scene-4.wav","tts/DollhouseDread-scene-5.wav","tts/DollhouseDread-scene-6.wav","tts/DollhouseDread-scene-7.wav","tts/DollhouseDread-scene-8.wav","tts/DollhouseDread-scene-9.wav"]}
    />
  );
};
