import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const ElvisRoastReel: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-playfair), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"minimal"}
      theme={"magazine"}
      motionFeel={"smooth"}
      transitionEnergy={"high"}
      gradePreset={"neutral_punch"}
      sceneLengthInFrames={182}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE AUDACITY OF THIS LOOK.",
          "kicker": "the blonde doll and the cigarette are doing too much, sir.",
          "accent": "#FFCC00",
          "transition": "flash-cut",
          "narration": "Look at this doll. The blonde doll and the cigarette are doing too much, sir.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "WE NEED TO TALK ABOUT THE HAIR.",
          "kicker": "the red mask and the smoke are a whole mood, bestie no.",
          "accent": "#880000",
          "transition": "wipe-right",
          "narration": "The red mask and the smoke are a whole mood, bestie no.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "SIR, THIS IS A WENDY'S.",
          "kicker": "the patterned jacket and yellow shirt are a crime, bro.",
          "accent": "#ffd700",
          "transition": "slide-left",
          "narration": "This jacket and yellow shirt combo? Sir, this is a Wendy's.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "BESTIE NO. THE PINK HAIR.",
          "kicker": "the dramatic pose and the window frame are overkill, ma'am.",
          "accent": "#ff69b4",
          "transition": "flip",
          "narration": "The pink hair and the dramatic pose through the window? Overkill, ma'am.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE CLOWN ENERGY IS TOO MUCH.",
          "kicker": "two figures in the open window are giving 'too much' vibes.",
          "accent": "#666666",
          "transition": "chromatic-split",
          "narration": "The clown energy is too much. These two figures are giving way too much.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "MANNERISMS ARE UNSETTLING.",
          "kicker": "the red-faced clown is just too intense for one night.",
          "accent": "#8b0000",
          "transition": "wipe-bottom",
          "narration": "The red-faced clown is just too intense. Nobody needs this level of performance.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "POV: THE STYLING IS A MESS.",
          "kicker": "the suit and the cigarette are doing all the talking, sir.",
          "accent": "#34495e",
          "transition": "slide-right",
          "narration": "POV: The styling is a mess. The suit and the cigarette are doing all the talking.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE GLAMOUR IS FAKE.",
          "kicker": "the silver jacket and cigarette are just too polished, tell me why.",
          "accent": "#5d6d7e",
          "transition": "fade",
          "narration": "The silver jacket and cigarette look polished, but we all know the truth.",
          "textPlacement": "bottom-left"
        }
      ]}
      sceneTTSPaths={["tts/ElvisRoastReel-scene-0.wav","tts/ElvisRoastReel-scene-1.wav","tts/ElvisRoastReel-scene-2.wav","tts/ElvisRoastReel-scene-3.wav","tts/ElvisRoastReel-scene-4.wav","tts/ElvisRoastReel-scene-5.wav","tts/ElvisRoastReel-scene-6.wav","tts/ElvisRoastReel-scene-7.wav"]}
    />
  );
};
