import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const GLITCHRAW: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      scenes={[
        {
          "src": "uploads/d0385e3b5b.png",
          "caption": "IMPACT",
          "kicker": "system failure imminent",
          "accent": "#4cc9ff",
          "transition": "fade"
        },
        {
          "src": "uploads/2bbf83280c.png",
          "caption": "VELOCITY",
          "kicker": "breaking the frame rate",
          "accent": "#ff3d3d",
          "transition": "slide-right"
        },
        {
          "src": "uploads/913197aeec.png",
          "caption": "SIGNAL",
          "kicker": "lost in the static noise",
          "accent": "#a78bfa",
          "transition": "flip"
        },
        {
          "src": "uploads/36cf195587.png",
          "caption": "ECHO",
          "kicker": "the moment repeats",
          "accent": "#ff8a2a",
          "transition": "wipe"
        },
        {
          "src": "uploads/cc49cef394.png",
          "caption": "BREAK",
          "kicker": "reality fractured",
          "accent": "#8ab4ff",
          "transition": "fade"
        }
      ]}
    />
  );
};
