import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const GLITCHREEL: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      scenes={[
        {
          "src": "uploads/2bbf83280c.png",
          "caption": "CHAOS",
          "kicker": "system overload",
          "accent": "#4cc9ff",
          "transition": "wipe"
        },
        {
          "src": "uploads/cc49cef394.png",
          "caption": "SIGNAL",
          "kicker": "rebooting the frame",
          "accent": "#a78bfa",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
