import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MidnightReflections: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={463}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE SMOKE AND THE GLASS",
          "kicker": "some secrets are best kept hazy, caught between the reflection and the smoke. you never knew the story until the moment the light shifted.",
          "accent": "#333333",
          "transition": "fade"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "WHO IS WATCHING US?",
          "kicker": "the car was empty, but the feeling of being observed was thick, like the scent of stale smoke and forgotten promises.",
          "accent": "#1a1a1a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "PINK HAIR, LOST ROADS",
          "kicker": "every journey has a soundtrack, and sometimes, the best memories are the ones you can only hear echoing through the passing years.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE GRIT OF THE NIGHT",
          "kicker": "it wasn't the cigarette, it was the silence between the breaths—the weight of everything unsaid, hanging in the humid air.",
          "accent": "#8b0000",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "LOOK ME IN THE EYE",
          "kicker": "you thought you knew the story, but the truth always has a sharper edge, a look that cuts through the haze and leaves you breathless.",
          "accent": "#a0522d",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE SECRET PASSENGER",
          "kicker": "they didn't want to be seen, but the moment they leaned out, the whole world seemed to hold its breath, waiting for the next move.",
          "accent": "#4c6d5c",
          "transition": "slide-left"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "WHISPERS BY THE WINDOW",
          "kicker": "some connections are fleeting, beautiful, and only exist in the soft, smoky glow of a late-night conversation.",
          "accent": "#a08c7b",
          "transition": "fade"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE END OF THE LINE",
          "kicker": "the smoke clears, the car pulls away, and all that's left is the echo of a story you'll never quite piece together.",
          "accent": "#5c3a2e",
          "transition": "flip"
        }
      ]}
    />
  );
};
