import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MidnightManifesto: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={78}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "NEVER LOOK BACK.",
          "kicker": "the city lights blur into a haze of neon and regret. this is the moment you disappear.",
          "accent": "#ff69b4",
          "transition": "wipe"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE VIBE IS IMMORTAL.",
          "kicker": "we don't follow the rules; we set the pace. raw energy, zero filter.",
          "accent": "#FF6600",
          "transition": "slide-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "SINISTER. UNSEEN. UNSTOPPABLE.",
          "kicker": "the truth is always lurking just outside the frame. don't trust the smile.",
          "accent": "#cc0000",
          "transition": "flip"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE GAZE. THE CONFRONTATION.",
          "kicker": "you think you know the story, but you haven't seen the ending. it's always darker.",
          "accent": "#FFC300",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "GRIT. REBELLION. CODE.",
          "kicker": "this is the underground aesthetic. lived-in, damaged, and completely authentic.",
          "accent": "#a03322",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "CINEMATIC. RAW. UNFILTERED.",
          "kicker": "the moment the music drops and everything else fades out. pure, kinetic energy.",
          "accent": "#004d40",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "SULTRY. ELECTRIC. NIGHT.",
          "kicker": "the kind of moment you wish would never end, but know you can't repeat.",
          "accent": "#a08a76",
          "transition": "fade"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE MYSTERY. THE SMOKE.",
          "kicker": "she knows something you don't. the secrets are always whispered in the dark.",
          "accent": "#a0522d",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "BOLD. DEFIANT. PINK.",
          "kicker": "don't apologize for the chaos. wear your defiance like armor.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "NO RULES. NO LIMITS.",
          "kicker": "the spirit of the road. always moving, always burning bright.",
          "accent": "#333333",
          "transition": "slide-left"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE LOOK. THE STARE.",
          "kicker": "it's not about where you're going, it's about the intensity of the ride.",
          "accent": "#a8dadc",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "GOLDEN HOUR. GOLDEN SIN.",
          "kicker": "the cinematic glow of a perfect, reckless night. save this for the mood.",
          "accent": "#ffd43a",
          "transition": "slide-top"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLOW. THE EDGE.",
          "kicker": "a beautiful, dangerous moment captured forever. the smoke never clears.",
          "accent": "#1a1a1a",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE MANIFESTO. THE POWER.",
          "kicker": "commanding attention. the kind of presence that stops the world in its tracks.",
          "accent": "#2F4F4F",
          "transition": "flip"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE GRIND. THE REALITY.",
          "kicker": "this is the raw footage of life. imperfect, intense, and totally yours.",
          "accent": "#1e3d41",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "UNBOTHERED. UNSTOPPABLE.",
          "kicker": "the confidence that comes from knowing your own rhythm. feel the beat.",
          "accent": "#0077aa",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE TRICK. THE SHOW.",
          "kicker": "never underestimate the performance. the unsettling art of the moment.",
          "accent": "#1a232e",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE VIBE CHECK. PASS.",
          "kicker": "if you feel this, you understand the assignment. cinematic chaos.",
          "accent": "#a8dadc",
          "transition": "fade"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "FOREVER. IN THE MOMENT.",
          "kicker": "the perfect, fleeting memory. capture the light, embrace the dark.",
          "accent": "#333333",
          "transition": "slide-top"
        }
      ]}
    />
  );
};
