import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MidnightCruise: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLOW UP IS REAL.",
          "kicker": "Some secrets are best left shrouded in smoke and red light. Don't look too close.",
          "accent": "#FF0000"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "DON'T LOOK BACK.",
          "kicker": "The things you see in the rearview mirror are never what they seem.",
          "accent": "#cc0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "RAW ENERGY ONLY.",
          "kicker": "Every exhale is a statement. Every moment is cinematic.",
          "accent": "#a03321",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "VIBE CHECK: PASSED.",
          "kicker": "Serving main character energy since forever. This is the aesthetic.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE ORIGINAL MOOD.",
          "kicker": "Some things just have that timeless, undeniable gravitas.",
          "accent": "#b88600",
          "transition": "slide-left"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "ELEGANCE IN THE SMOKE.",
          "kicker": "The kind of quiet confidence that needs no explanation. Just the moment.",
          "accent": "#808080",
          "transition": "wipe"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "GRIT. NO FILTERS.",
          "kicker": "This is the soundtrack to the nights you won't forget. Pure, raw cinema.",
          "accent": "#e65100",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE ENDING SHOT.",
          "kicker": "Keep the camera rolling. The story never stops.",
          "accent": "#a0522d",
          "transition": "fade"
        }
      ]}
    />
  );
};
