import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MidnightRun: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={182}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "NIGHT DRIVE VIBES",
          "kicker": "the city lights blur into a permanent haze, and you realize you're not alone in the backseat.",
          "accent": "#333333"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE VIBE IS IMMACULATE",
          "kicker": "every corner of this town looks like it was filmed on expired film stock and bad decisions.",
          "accent": "#ff6600",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "ALWAYS LOOKING FOR THE DRAMA",
          "kicker": "they said the best stories happen after midnight, and they were right.",
          "accent": "#a08040",
          "transition": "flip"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "PINK HAIR, BAD DECISIONS",
          "kicker": "some nights you just need a blast of neon and zero regrets.",
          "accent": "#ff69b4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "WHO IS WATCHING US?",
          "kicker": "the unsettling things are always in the periphery, right? don't look directly at the clown.",
          "accent": "#cc0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "GRIT. RAW. CINEMATIC.",
          "kicker": "the kind of portrait that feels like it was taken at 3 AM, fueled by smoke and adrenaline.",
          "accent": "#a0331d",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE SECRET PASSENGERS",
          "kicker": "you never know who's riding shotgun until they make eye contact.",
          "accent": "#4a695a",
          "transition": "fade"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE LAST STOP",
          "kicker": "just the smoke, the streetlights, and the promise of a story you'll never tell.",
          "accent": "#A08C77",
          "transition": "slide-right"
        }
      ]}
    />
  );
};
