import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MidnightDriveMood: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={197}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE VIBE IS IMMORTAL.",
          "kicker": "some nights you just need a classic car and a cigarette to feel like the main character.",
          "accent": "#a08040"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "PINK HAIR, ALL THE GLAMOUR.",
          "kicker": "when the outfit is fire and the smoke is thicker. save this for inspo.",
          "accent": "#f1c40f",
          "transition": "slide-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "DON'T LOOK BACK.",
          "kicker": "the kind of secret you keep locked in the back seat. creepy cinematic energy.",
          "accent": "#cc0000",
          "transition": "flip"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "JUST LOOK AT ME.",
          "kicker": "the kind of smoke that tastes like regret and expensive perfume. mood board material.",
          "accent": "#a08e7a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "RETRO NIGHT DRIVE.",
          "kicker": "every moment feels like a scene from a forgotten 80s movie. cinematic.",
          "accent": "#e84a2c",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE MAIN CHARACTER ENERGY.",
          "kicker": "you know the score. the smoke, the stare, the perfect moment. pure rebellion.",
          "accent": "#006400",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "GRIT. NO FILTER.",
          "kicker": "some stories are best told in the smoke and the neon glow. end scene.",
          "accent": "#e65100",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
