import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const Momentum: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      scenes={[
        {
          "src": "uploads/31d1ed6165.png",
          "caption": "VELOCITY",
          "kicker": "the asphalt calls",
          "accent": "#ff3d3d",
          "transition": "fade"
        },
        {
          "src": "uploads/7b1932ef9e.png",
          "caption": "POWER",
          "kicker": "engine roar, pure adrenaline",
          "accent": "#ff8a2a",
          "transition": "wipe"
        },
        {
          "src": "uploads/eaed89d618.png",
          "caption": "LEGENDS",
          "kicker": "the court awaits greatness",
          "accent": "#ffb72a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/9ab4e2c73a.png",
          "caption": "ESCAPE",
          "kicker": "where the horizon meets peace",
          "accent": "#4cc9ff",
          "transition": "slide-top"
        },
        {
          "src": "uploads/49edf50552.png",
          "caption": "GROWTH",
          "kicker": "slow moments, deep roots",
          "accent": "#6cd97a",
          "transition": "flip"
        }
      ]}
    />
  );
};
