import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MondayWakeUpCall: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      gradePreset={"warm_cinematic"}
      sceneLengthInFrames={155}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POV: MONDAY MORNING",
          "kicker": "The simulation needs a hard reboot. Time to ship it.",
          "accent": "#ff3d3d",
          "transition": "wipe-right",
          "narration": "POV: Monday morning. The simulation needs a hard reboot. Time to ship it."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "WAKE UP, ELVIS.",
          "kicker": "It’s not a costume party. It’s a Monday.",
          "accent": "#ff8a2a",
          "transition": "slide-left",
          "narration": "Wake up, Elvis. It's not a costume party. It's a Monday."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THIS IS WHY.",
          "kicker": "You gotta iterate past the nostalgia.",
          "accent": "#ff3d3d",
          "transition": "flip",
          "narration": "This is why. You gotta iterate past the nostalgia."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "420 ISN'T A DAY.",
          "kicker": "It's a mindset. Get back to the stack.",
          "accent": "#ff8a2a",
          "transition": "slide-top",
          "narration": "420 isn't a day. It's a mindset. Get back to the stack."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "STOP MOCKING.",
          "kicker": "The throughput demands focus, not smoke breaks.",
          "accent": "#ff3d3d",
          "transition": "wipe-bottom",
          "narration": "Stop mocking. The throughput demands focus, not smoke breaks."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "BUILD. DEPLOY. REPEAT.",
          "kicker": "No time for the curtain calls. Ship it.",
          "accent": "#ff8a2a",
          "transition": "slide-right",
          "narration": "Build. Deploy. Repeat. No time for the curtain calls. Ship it."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE TRUTH ABOUT.",
          "kicker": "Product-market fit hits before the encore.",
          "accent": "#4a5568",
          "transition": "fade",
          "narration": "The truth about it. Product-market fit hits before the encore."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "GET UP. IT'S MONDAY.",
          "kicker": "Your best version deploys at 9 AM sharp.",
          "accent": "#ff3d3d",
          "transition": "wipe-right",
          "narration": "Get up. It's Monday. Your best version deploys at 9 AM sharp."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "OWN THE WEEK.",
          "kicker": "Save this reel for when you need the kickstart.",
          "accent": "#ff8a2a",
          "transition": "clock-wipe",
          "narration": "Own the week. Save this reel for when you need the kickstart."
        }
      ]}
      sceneTTSPaths={["tts/MondayWakeUpCall-scene-0.wav","tts/MondayWakeUpCall-scene-1.wav","tts/MondayWakeUpCall-scene-2.wav","tts/MondayWakeUpCall-scene-3.wav","tts/MondayWakeUpCall-scene-4.wav","tts/MondayWakeUpCall-scene-5.wav","tts/MondayWakeUpCall-scene-6.wav","tts/MondayWakeUpCall-scene-7.wav","tts/MondayWakeUpCall-scene-8.wav"]}
    />
  );
};
