import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const MountainEscape: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={110}
      transitionLengthInFrames={24}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "ESCAPE MODE ACTIVATED.",
          "kicker": "where the only view is the mountain.",
          "accent": "#a19b8d",
          "transition": "fade"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "THE VIEW CHANGES EVERYTHING.",
          "kicker": "finding peace in the dramatic silence.",
          "accent": "#4682B4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "WAKING UP TO THIS.",
          "kicker": "a perfect, snowy morning ritual.",
          "accent": "#a3c1ad",
          "transition": "slide-right"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "THIS IS THE VIBE.",
          "kicker": "cinematic moments, forever.",
          "accent": "#5a7d6e",
          "transition": "fade"
        }
      ]}
    />
  );
};
