import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const NeoFuturism: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "POWER",
          "kicker": "the future awaits",
          "accent": "#ffd43a"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "ASCEND",
          "kicker": "rising above the noise",
          "accent": "#4cc9ff",
          "transition": "slide-right"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "ETERNITY",
          "kicker": "timeless design",
          "accent": "#a78bfa",
          "transition": "flip"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "VISION",
          "kicker": "where reality bends",
          "accent": "#ffb72a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "LEGACY",
          "kicker": "forever in motion",
          "accent": "#8ab4ff",
          "transition": "fade"
        }
      ]}
    />
  );
};
