import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const NeonSwagger: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={117}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/91933ae417.png",
          "caption": "WARNING: DO NOT LOOK.",
          "kicker": "the night has a mouth, and it smells like gasoline and cheap cigarettes.",
          "accent": "#cc9900",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE STREETS CALL.",
          "kicker": "you don't need a map when the beat is this loud.",
          "accent": "#006666",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "GLOW UP. NO FILTER.",
          "kicker": "this is the soundtrack to your best mistakes.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "SMOKE & ASPHALT.",
          "kicker": "the kind of smoke that tastes like regret and freedom.",
          "accent": "#e05200",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "LOCKED IN.",
          "kicker": "the moment the neon buzz hits and you forget your name.",
          "accent": "#cc3300",
          "transition": "wipe"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE MUSE.",
          "kicker": "sometimes the most dramatic things are just plastic and smoke.",
          "accent": "#8b0000",
          "transition": "slide-top"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "ELEGANCE. IN THE CHAOS.",
          "kicker": "keep the windows down and the secrets flowing.",
          "accent": "#a08a70",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "NEVER STOP MOVING.",
          "kicker": "the city never sleeps, and neither do we.",
          "accent": "#a0522d",
          "transition": "flip"
        }
      ]}
    />
  );
};
