import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const NeonRebel: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={133}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "GLOW UP OR GET LEFT BEHIND",
          "kicker": "the smoke clears, the truth is revealed.",
          "accent": "#ff0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "NEVER LOOK BACK",
          "kicker": "the carnival never sleeps, the secrets are always visible.",
          "accent": "#8b0000",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE GRIT IS REAL",
          "kicker": "don't ask questions, just ride the wave.",
          "accent": "#a0331e",
          "transition": "flip"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "EYE CONTACT ONLY",
          "kicker": "you can't escape the stare.",
          "accent": "#3a5c4a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "UNBOTHERED VIBES",
          "kicker": "just cruising through the neon haze.",
          "accent": "#424242",
          "transition": "wipe"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POP CULTURE SHOCK",
          "kicker": "the past is loud, the future is brighter.",
          "accent": "#ff69b4",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE MAIN CHARACTER ENERGY",
          "kicker": "keep it low key, but make it unforgettable.",
          "accent": "#5c4033",
          "transition": "fade"
        }
      ]}
    />
  );
};
