import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const NeonNoirDrive: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={118}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE CITY NEVER SLEEPS",
          "kicker": "another night, another secret whispered through the exhaust fumes.",
          "accent": "#cc3300",
          "transition": "wipe-right",
          "narration": "The city never sleeps. Another night, another secret whispered through the exhaust fumes."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "MID-CENTURY GRIT",
          "kicker": "the smoke hangs heavy, a curtain drawn on forgotten moments.",
          "accent": "#a04040",
          "transition": "slide-left",
          "narration": "Mid-century grit. The smoke hangs heavy, a curtain drawn on forgotten moments."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POP ART ENERGY",
          "kicker": "the vibrant chaos of a summer blockbuster memory.",
          "accent": "#ff8c00",
          "transition": "flip",
          "narration": "Pop art energy. The vibrant chaos of a summer blockbuster memory."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "HIGH CONTRAST DRAMA",
          "kicker": "every scowl tells a story you'll never piece together.",
          "accent": "#cc3300",
          "transition": "slide-right",
          "narration": "High contrast drama. Every scowl tells a story you'll never piece together."
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "RED EYES, RED LIGHTS",
          "kicker": "the mystery behind the red eye mask lingers in the rearview.",
          "accent": "#a04040",
          "transition": "wipe-bottom",
          "narration": "Red eyes, red lights. The mystery behind the red eye mask lingers in the rearview."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE FINAL ACT",
          "kicker": "the engine idles down, leaving only the echo of the smoke.",
          "accent": "#222222",
          "transition": "slide-top",
          "narration": "The final act. The engine idles down, leaving only the echo of the smoke."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "PULP FICTION VIBES",
          "kicker": "a perfect blend of grit and manufactured, neon-drenched cool.",
          "accent": "#ff6600",
          "transition": "fade",
          "narration": "Pulp fiction vibes. A perfect blend of grit and manufactured, neon-drenched cool."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "RAW MOMENT CAPTURE",
          "kicker": "just the moment before the curtain drops, suspended in smoke.",
          "accent": "#333333",
          "transition": "clock-wipe",
          "narration": "Raw moment capture. Just the moment before the curtain drops, suspended in smoke."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "STILLNESS BEFORE THE RUSH",
          "kicker": "the silence after the last word, the cigarette smoke drifting slow.",
          "accent": "#1c1c1c",
          "transition": "wipe-right",
          "narration": "Stillness before the rush. The silence after the last word, the cigarette smoke drifting slow."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "VIBRANT STORYTELLING",
          "kicker": "this whole scene feels like a fever dream on 8mm film.",
          "accent": "#ff8c00",
          "transition": "slide-left",
          "narration": "Vibrant storytelling. This whole scene feels like a fever dream on 8mm film."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "NEON NOIR",
          "kicker": "don't trust the smile, or the smoke, or the neon glow.",
          "accent": "#a04040",
          "transition": "flip",
          "narration": "Neon Noir. Don't trust the smile, or the smoke, or the neon glow."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE GLITCH EFFECT",
          "kicker": "a momentary break in the signal, a flicker of truth.",
          "accent": "#cc3300",
          "transition": "fade",
          "narration": "The glitch effect. A momentary break in the signal, a flicker of truth."
        }
      ]}
      sceneTTSPaths={["tts/NeonNoirDrive-scene-0.wav","tts/NeonNoirDrive-scene-1.wav","tts/NeonNoirDrive-scene-2.wav","tts/NeonNoirDrive-scene-3.wav","tts/NeonNoirDrive-scene-4.wav","tts/NeonNoirDrive-scene-5.wav","tts/NeonNoirDrive-scene-6.wav","tts/NeonNoirDrive-scene-7.wav","tts/NeonNoirDrive-scene-8.wav","tts/NeonNoirDrive-scene-9.wav","tts/NeonNoirDrive-scene-10.wav","tts/NeonNoirDrive-scene-11.wav"]}
    />
  );
};
