import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const NIGHTDRIVEGLITCH: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={86}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE VIBE IS EVERYTHING",
          "kicker": "you don't just enter the moment, you become it. urban defiance.",
          "accent": "#ff6600",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "SULTRY. UNFILTERED.",
          "kicker": "the metallic jacket, the smoke, the endless night. pure cinematic energy.",
          "accent": "#a08060",
          "transition": "flip"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "RETRO. GLITCH. POP.",
          "kicker": "pink hair, neon glow, and the perfect smoke break. a throwback anthem.",
          "accent": "#FF69B4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "STARE DOWN. NO MERCY.",
          "kicker": "the gaze is the weapon. don't blink, or you'll miss the moment.",
          "accent": "#e6b33a",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "DANGER. ELECTRIFIED.",
          "kicker": "the red mask, the smoke, the silent promise. this is the after-hours kind of trouble.",
          "accent": "#8b0000",
          "transition": "slide-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "SINISTER. NIGHT. CALLING.",
          "kicker": "the clown aesthetic meets the asphalt. a beautiful, unsettling chaos.",
          "accent": "#cc0000",
          "transition": "flip"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "RAW. UNHINGED. VIBES.",
          "kicker": "the grit is real. this is the moment before the beat drops. cinematic tension.",
          "accent": "#333333",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE LOOK. THE POWER.",
          "kicker": "suit and smoke. he owns the frame. the ultimate power move.",
          "accent": "#225435",
          "transition": "slide-top"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "DEFIANCE. ALWAYS.",
          "kicker": "the same energy, a different angle. the spirit of the city never fades.",
          "accent": "#ff6600",
          "transition": "slide-left"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "VINTAGE. GLOW. HIT.",
          "kicker": "the retro cool is a mood. capturing the perfect, electric moment in time.",
          "accent": "#2299CC",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "ICONIC. GOLD. ERA.",
          "kicker": "the confidence is palpable. a timeless portrait of nocturnal glamour.",
          "accent": "#c2c2c2",
          "transition": "flip"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE SECRET. KEEP IT.",
          "kicker": "the mask hides everything, but the smoke tells the story. mystery defined.",
          "accent": "#1a1a1a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE GAZE. THE TRUTH.",
          "kicker": "it's not just a look; it's a declaration. the intensity is unmatched.",
          "accent": "#800000",
          "transition": "slide-top"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "CINEMATIC. GRIT. CORE.",
          "kicker": "the raw footage aesthetic. capturing the beautiful mess of the city night.",
          "accent": "#8b0000",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "WARNING: UNHINGED.",
          "kicker": "the perfect blend of unsettling and captivating. never underestimate the clown.",
          "accent": "#223338",
          "transition": "clock-wipe"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE ENERGY. UNSTOPPABLE.",
          "kicker": "this is the beat drop. the moment everything clicks into place. feel the rhythm.",
          "accent": "#ff6600",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "ENDLESS. NIGHT. DRIVE.",
          "kicker": "save this reel for when you need that cinematic, high-octane motivation.",
          "accent": "#331a00",
          "transition": "fade"
        }
      ]}
    />
  );
};
