import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const PlasticDecay: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-fraunces), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"film"}
      sceneLengthInFrames={94}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE VOID STARTS HERE.",
          "kicker": "we were built to break. the facade is cracking.",
          "accent": "#ff3d3d",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "UNFILTERED. RAW. ANGRY.",
          "kicker": "this is the truth behind the perfect smile. the glitch.",
          "accent": "#a78bfa",
          "transition": "flip"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "DON'T LOOK AWAY.",
          "kicker": "the silence is louder than the scream. feel the pressure.",
          "accent": "#ff8a2a",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "CONSUME THE CHAOS.",
          "kicker": "we are the product. we are the poison. we are the art.",
          "accent": "#ff3d3d",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "PERFECTLY BROKEN.",
          "kicker": "the veneer is peeling. the rot is visible.",
          "accent": "#6c3d3d",
          "transition": "fade"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE WEIGHT OF IT ALL.",
          "kicker": "every cigarette burns a little piece of the soul. watch it fade.",
          "accent": "#8b4513",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "REALITY IS A LIE.",
          "kicker": "you think you know the script, but the script is burning.",
          "accent": "#ff6fb5",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE END OF THE LINE.",
          "kicker": "the performance is over. the curtain drops on the plastic dream.",
          "accent": "#444444",
          "transition": "flip"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THIS IS THE HOOK.",
          "kicker": "you can't unsee this. the moment the mask slipped.",
          "accent": "#ff3d3d",
          "transition": "slide-top"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "WARNING: DISTURBING.",
          "kicker": "don't scroll past this feeling. let the dissonance hit.",
          "accent": "#a78bfa",
          "transition": "fade"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE GLITCH IN THE SYSTEM.",
          "kicker": "the manufactured anger. the perfect, toxic rebellion.",
          "accent": "#ff8a2a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "EMBRACE THE DECAY.",
          "kicker": "it's not about the fire, it's about the ash. the aftermath.",
          "accent": "#ff3d3d",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE ECHO CHAMBER.",
          "kicker": "we are all just repeating the same toxic narrative. listen closely.",
          "accent": "#6c3d3d",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "NO ESCAPE.",
          "kicker": "the smoke never clears. the plastic always remains.",
          "accent": "#8b4513",
          "transition": "flip"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "YOU ARE THE PRODUCT.",
          "kicker": "the ultimate consumer of manufactured despair. save this reel.",
          "accent": "#ff6fb5",
          "transition": "fade"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "BRUTAL. CINEMATIC. RAW.",
          "kicker": "the final frame. the unsettling truth. (link in bio)",
          "accent": "#444444",
          "transition": "clock-wipe"
        }
      ]}
    />
  );
};
