import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const Reel420WakeUp: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      gradePreset={"neutral_punch"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "POV: ELVIS IS STILL SLEEPING",
          "kicker": "the curtain drops. time to wake up, man. this ain't no encore.",
          "accent": "#990000",
          "transition": "wipe-right",
          "narration": "POV: Elvis is still sleeping. The curtain drops. Time to wake up, man. This ain't no encore."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "STILL DREAMING OF THE SHOW",
          "kicker": "the smoke clears, the spotlight hits. you gotta move, baby.",
          "accent": "#ff6600",
          "transition": "flip",
          "narration": "Still dreaming of the show. The smoke clears, the spotlight hits. You gotta move, baby."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "MID-CENTURY SLACKER",
          "kicker": "the swagger's faded. the era's over. hit deploy.",
          "accent": "#ffcc00",
          "transition": "slide-left",
          "narration": "The swagger's faded. The era's over. Hit deploy."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POP CULTURE OVERLOAD",
          "kicker": "this whole vibe is a glitch. refactor the whole damn thing.",
          "accent": "#ff69b4",
          "transition": "wipe-bottom",
          "narration": "This whole vibe is a glitch. Refactor the whole damn thing."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "RETRO HORROR CORE",
          "kicker": "the clown makeup is peeling. the curtain's coming down, clown.",
          "accent": "#ff4500",
          "transition": "slide-right",
          "narration": "The clown makeup is peeling. The curtain's coming down, clown."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "INTENSE, BUT STILL SLOW",
          "kicker": "the performance stalls. need more throughput, less smoke.",
          "accent": "#ff8c00",
          "transition": "fade",
          "narration": "The performance stalls. Need more throughput, less smoke."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "SUIT UP. GET TO WORK.",
          "kicker": "the suit fits, but the energy doesn't. ship it, man.",
          "accent": "#a08c6c",
          "transition": "clock-wipe",
          "narration": "Suit up. Get to work. The suit fits, but the energy doesn't. Ship it, man."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "FINAL CALL. WAKE UP.",
          "kicker": "save this for when you finally decide to move fast. follow for more.",
          "accent": "#c0b0a0",
          "narration": "Final call. Wake up. Save this for when you finally decide to move fast. Follow for more."
        }
      ]}
      sceneTTSPaths={["tts/Reel420WakeUp-scene-0.wav","tts/Reel420WakeUp-scene-1.wav","tts/Reel420WakeUp-scene-2.wav","tts/Reel420WakeUp-scene-3.wav","tts/Reel420WakeUp-scene-4.wav","tts/Reel420WakeUp-scene-5.wav","tts/Reel420WakeUp-scene-6.wav","tts/Reel420WakeUp-scene-7.wav"]}
    />
  );
};
