import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const RoastTheIcon: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      gradePreset={"warm_cinematic"}
      sceneLengthInFrames={110}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "WHO'S STILL DOING THIS?",
          "kicker": "The smoke, the suit, the sheer audacity. We see you.",
          "accent": "#ff3d3d",
          "transition": "wipe-right",
          "narration": "Seriously? Still doing this look? The smoke, the suit, the sheer audacity. We see you."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "ACTING LIKE IT'S 1955",
          "kicker": "The whole 'cool' act is running on outdated firmware, buddy.",
          "accent": "#ff3d3d",
          "transition": "slide-left",
          "narration": "Acting like it's 1955. The whole 'cool' act is running on outdated firmware, buddy."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE PLASTIC LOOK IS REAL",
          "kicker": "It's not mystery, it's just bad lighting and bad habits.",
          "accent": "#ff3d3d",
          "transition": "flip",
          "narration": "The plastic look is real. It's not mystery, it's just bad lighting and bad habits."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THINK YOU'RE STILL A VIBE?",
          "kicker": "Your whole aesthetic is buffering. Needs a major refactor.",
          "accent": "#ff3d3d",
          "transition": "slide-bottom",
          "narration": "Think you're still a vibe? Your whole aesthetic is buffering. Needs a major refactor."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "UNPOPULAR OPINION:",
          "kicker": "The smoke machine is busted. You're exposed.",
          "accent": "#ff3d3d",
          "transition": "wipe",
          "narration": "Unpopular opinion: The smoke machine is busted. You're exposed."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "TOO MUCH DRAMA, MAN",
          "kicker": "The performance art is over. Time to deploy the logout.",
          "accent": "#ff3d3d",
          "transition": "slide-right",
          "narration": "Too much drama, man. The performance art is over. Time to deploy the logout."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "NIGHTLIFE ISN'T A COSTUME",
          "kicker": "The 'effortless' look requires actual effort. Check the metrics.",
          "accent": "#a78bfa",
          "transition": "slide-top",
          "narration": "Nightlife isn't a costume. The 'effortless' look requires actual effort. Check the metrics."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "GLAMOUR ISN'T FREE",
          "kicker": "This whole 'sultry' vibe? It's running on deprecated code.",
          "accent": "#d2b48c",
          "transition": "clock-wipe",
          "narration": "Glamour isn't free. This whole 'sultry' vibe? It's running on deprecated code."
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "SAVE THIS FOR LATER:",
          "kicker": "Proof that some things never iterate past version 1.0.",
          "accent": "#ff3d3d",
          "transition": "fade",
          "narration": "Save this for later. Proof that some things never iterate past version 1.0."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE TRUTH ABOUT IT:",
          "kicker": "You peaked in the 90s. We're on 2024 stack.",
          "accent": "#ff3d3d",
          "transition": "wipe-bottom",
          "narration": "The truth about it. You peaked in the 90s. We're on 2024 stack."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "FAIL FAST. FAIL HARDER.",
          "kicker": "Stop trying to look like a character from a bad movie.",
          "accent": "#ff3d3d",
          "transition": "slide-left",
          "narration": "Fail fast. Fail harder. Stop trying to look like a character from a bad movie."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "YOUR OUTPUT IS LATENCY.",
          "kicker": "The throughput on this whole persona is dangerously low.",
          "accent": "#ff3d3d",
          "transition": "slide-right",
          "narration": "Your output is latency. The throughput on this whole persona is dangerously low."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "FOLLOW FOR MORE:",
          "kicker": "The roast continues. Don't miss the next deployment.",
          "accent": "#d2b48c",
          "transition": "iris",
          "narration": "Follow for more. The roast continues. Don't miss the next deployment."
        }
      ]}
      sceneTTSPaths={["tts/RoastTheIcon-scene-0.wav","tts/RoastTheIcon-scene-1.wav","tts/RoastTheIcon-scene-2.wav","tts/RoastTheIcon-scene-3.wav","tts/RoastTheIcon-scene-4.wav","tts/RoastTheIcon-scene-5.wav","tts/RoastTheIcon-scene-6.wav","tts/RoastTheIcon-scene-7.wav","tts/RoastTheIcon-scene-8.wav","tts/RoastTheIcon-scene-9.wav","tts/RoastTheIcon-scene-10.wav","tts/RoastTheIcon-scene-11.wav","tts/RoastTheIcon-scene-12.wav"]}
    />
  );
};
