import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const RoastingElvis: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      gradePreset={"warm_cinematic"}
      sceneLengthInFrames={158}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POV: Monday morning roast",
          "kicker": "He thought the charisma was permanent. Cute.",
          "accent": "#b05e40",
          "transition": "fade",
          "narration": "POV: Monday morning roast. He thought the charisma was permanent. Cute."
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "Effortless? Never.",
          "kicker": "The drape is getting dusty, Elvis.",
          "accent": "#c43333",
          "transition": "slide-left",
          "narration": "Effortless? Never. The drape is getting dusty, Elvis."
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "Silhouette check: Failed.",
          "kicker": "The whole 'cool' act is wearing thin, man.",
          "accent": "#cc4422",
          "transition": "wipe-right",
          "narration": "Silhouette check: Failed. The whole 'cool' act is wearing thin, man."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "Lowkey cringe moment.",
          "kicker": "Nobody asked for this level of performance art.",
          "accent": "#d4a36a",
          "transition": "slide-bottom",
          "narration": "Lowkey cringe moment. Nobody asked for this level of performance art."
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "The archive footage.",
          "kicker": "We found the receipts, Elvis. You can't hide this.",
          "accent": "#d4a36a",
          "transition": "flip",
          "narration": "The archive footage. We found the receipts, Elvis. You can't hide this."
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "Vibe check: Failed.",
          "kicker": "That jacket was a fever dream, not a look.",
          "accent": "#ff7f00",
          "transition": "slide-top",
          "narration": "Vibe check: Failed. That jacket was a fever dream, not a look."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "It's giving... nothing.",
          "kicker": "Just the Monday morning haze, really.",
          "accent": "#3a2d2d",
          "transition": "fade",
          "narration": "It's giving... nothing. Just the Monday morning haze, really."
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "No cap, this is rough.",
          "kicker": "We're just keeping it 100 with you today.",
          "accent": "#1a1a1a",
          "transition": "wipe-bottom",
          "narration": "No cap, this is rough. We're just keeping it 100 with you today."
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "Save this for later.",
          "kicker": "Proof that some things never change. Follow for pt 2.",
          "accent": "#3a2d2d",
          "transition": "iris",
          "narration": "Save this for later. Proof that some things never change. Follow for pt 2."
        }
      ]}
      sceneTTSPaths={["tts/RoastingElvis-scene-0.wav","tts/RoastingElvis-scene-1.wav","tts/RoastingElvis-scene-2.wav","tts/RoastingElvis-scene-3.wav","tts/RoastingElvis-scene-4.wav","tts/RoastingElvis-scene-5.wav","tts/RoastingElvis-scene-6.wav","tts/RoastingElvis-scene-7.wav","tts/RoastingElvis-scene-8.wav"]}
    />
  );
};
