import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const StaticSignal: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLITCH IS REAL.",
          "kicker": "everything you thought was stable is just a signal delay. find the frequency.",
          "accent": "#333333",
          "transition": "wipe"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "DON'T LOOK BACK.",
          "kicker": "the things lurking in the periphery are always watching. they know your name.",
          "accent": "#cc9900",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "RAW ENERGY ONLY.",
          "kicker": "this isn't a moment, it's a permanent state of being. keep it dark.",
          "accent": "#e65100",
          "transition": "flip"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "FULL THROTTLE VIBES.",
          "kicker": "the neon burns brightest when you're running out of time. catch the wave.",
          "accent": "#ff69b4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "NO FILTER. NO ESCAPE.",
          "kicker": "the truth is always visible through the smoke. embrace the distortion.",
          "accent": "#cc3300",
          "transition": "wipe"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE SIGNAL IS CLEAR.",
          "kicker": "you have to look straight ahead, past the noise, to see the pattern.",
          "accent": "#2a4d3e",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "NIGHT DRIVE MODE.",
          "kicker": "the city breathes differently after midnight. you just have to wait for the beat.",
          "accent": "#a08060",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE ENDGAME IS HERE.",
          "kicker": "this is the moment the static clears. remember who you are.",
          "accent": "#c99c4e",
          "transition": "flip"
        }
      ]}
    />
  );
};
