import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const SummitView: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={38}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "SCALE",
          "kicker": "endless horizon line",
          "accent": "#4a6e7a",
          "transition": "wipe"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "ASCEND",
          "kicker": "reaching the summit",
          "accent": "#a08d6c",
          "transition": "slide-left"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "IMMENSE",
          "kicker": "the peak view",
          "accent": "#b0c4de",
          "transition": "slide-right"
        },
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "ZERO",
          "kicker": "minimalist escape",
          "accent": "#b0c4de",
          "transition": "flip"
        }
      ]}
    />
  );
};
