import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const SystemOverload: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={110}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "SYSTEM FAILURE IMMINENT",
          "kicker": "the signal degrades. everything breaks down to pure noise.",
          "accent": "#ff3d3d",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "ERROR: CORE MEMORY CORRUPT",
          "kicker": "can you even trust the feed anymore? the glitch is the truth.",
          "accent": "#ff8a2a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "NO SIGNAL. JUST STATIC.",
          "kicker": "we're past the narrative. this is the raw feed.",
          "accent": "#a78bfa",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLITCH IS THE MESSAGE.",
          "kicker": "don't look away. this is the unfiltered reality.",
          "accent": "#ff3d3d",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "REBOOTING THE FRAMEWORK.",
          "kicker": "every cycle resets the illusion. watch the seams tear.",
          "accent": "#ffb72a",
          "transition": "fade"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "CODE RED. MAXIMUM OVERLOAD.",
          "kicker": "the beat drops, the system crashes. feel the feedback.",
          "accent": "#ff3d3d",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "DECONSTRUCTING THE IMAGE.",
          "kicker": "what remains when the filters burn out? pure, raw signal.",
          "accent": "#8ab4ff",
          "transition": "slide-top"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "SYSTEM OVERRIDE INITIATED.",
          "kicker": "this isn't a story. it's the source code bleeding out.",
          "accent": "#ff3d3d",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "FEEDBACK LOOP DETECTED.",
          "kicker": "the repetition isn't random. it's the pattern emerging.",
          "accent": "#ff8a2a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THE TRUTH IS IN THE NOISE.",
          "kicker": "listen past the beat. feel the static hum beneath it all.",
          "accent": "#a78bfa",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "UNFILTERED. UNEDITED. RAW.",
          "kicker": "this is the moment the algorithm breaks. save this.",
          "accent": "#ffb72a",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "EMOTIONAL CORRUPTION.",
          "kicker": "the plastic facade cracks under the pressure of the beat.",
          "accent": "#ff3d3d",
          "transition": "slide-top"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "GLITCH ART: MAXIMUM IMPACT.",
          "kicker": "the beauty of the breakdown. the visceral, the brutal.",
          "accent": "#ff8a2a",
          "transition": "fade"
        }
      ]}
      sceneTTSPaths={["tts/SystemOverload-scene-0.wav","tts/SystemOverload-scene-1.wav","tts/SystemOverload-scene-2.wav","tts/SystemOverload-scene-3.wav","tts/SystemOverload-scene-4.wav","tts/SystemOverload-scene-5.wav","tts/SystemOverload-scene-6.wav","tts/SystemOverload-scene-7.wav","tts/SystemOverload-scene-8.wav","tts/SystemOverload-scene-9.wav","tts/SystemOverload-scene-10.wav","tts/SystemOverload-scene-11.wav","tts/SystemOverload-scene-12.wav"]}
    />
  );
};
