import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const SystemOverride: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-syne), 'Arial Black', system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), 'Courier New', monospace"}
      decorStyle={"minimal"}
      theme={"impact"}
      motionFeel={"snappy"}
      transitionEnergy={"high"}
      gradePreset={"neutral_punch"}
      sceneLengthInFrames={299}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THIS IS THE VIBE",
          "kicker": "PHASE 01 · NIGHT DRIVE",
          "accent": "#ff0000",
          "transition": "wipe-right",
          "narration": "This is the vibe. Phase one: Night Drive."
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "DIFFERENT BREED",
          "kicker": "SIGNAL INTERCEPTED",
          "accent": "#ff0000",
          "transition": "flip",
          "narration": "Different breed. Signal intercepted."
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THE ENDING THOUGH",
          "kicker": "MISSION COMPLETE",
          "accent": "#ff0000",
          "transition": "slide-left",
          "narration": "The ending thought. Mission complete."
        }
      ]}
    />
  );
};
