import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheArchitectureofSere: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={280}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "The Art of Empty Space.",
          "kicker": "Where design doesn't distract, it simply frames the world outside, making the view the ultimate piec",
          "accent": "#a0a090"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Embracing the Shadow.",
          "kicker": "Luxury isn't about shine; it's about the deep, quiet contrast between comfort and the wild, untamed ",
          "accent": "#4A7C8D",
          "transition": "slide-right"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "Blue Comfort, White Peaks.",
          "kicker": "Every detail, from the plush rug to the curved window, is a deliberate conversation with the surroun",
          "accent": "#4a5a70",
          "transition": "flip"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "The View as Masterpiece.",
          "kicker": "Some spaces don't just contain a view; they make the view the central, breathtaking element of the e",
          "accent": "#A9B2B8",
          "transition": "slide-left"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "Architecture Meets Nature.",
          "kicker": "The ultimate goal of design: to make you forget you are inside, and simply exist within the moment.",
          "accent": "#5a7d6e",
          "transition": "fade"
        }
      ]}
    />
  );
};
