import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheArtoftheView: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={280}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "The Art of the View",
          "kicker": "How natural light and expansive vistas redefine luxury living, making the landscape the ultimate des",
          "accent": "#A9B4B8"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "Framing the Horizon",
          "kicker": "Sophisticated design uses shadow and light to create depth, making the view the true centerpiece of ",
          "accent": "#a09070",
          "transition": "slide-right"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "Curving Lines, Open Spaces",
          "kicker": "Architectural flow is key. Curved windows maximize light and minimize visual barriers, connecting in",
          "accent": "#a3b1c1",
          "transition": "flip"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "Where Architecture Meets Nature",
          "kicker": "The perfect blend of man-made comfort and raw, untamed wilderness. A sanctuary built for contemplati",
          "accent": "#A9B5C1",
          "transition": "slide-left"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "The Embrace of Green",
          "kicker": "True luxury isn't about opulence; it's about the uninterrupted connection to the natural world.",
          "accent": "#4a6e5a",
          "transition": "fade"
        }
      ]}
    />
  );
};
