import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheBlueprintDesigning: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-fraunces), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"minimal"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "THE FOUNDATION OF DESIGN",
          "kicker": "Every great structure begins with a clear, symmetrical vision. We build on core principles of balanc",
          "accent": "#004d40",
          "transition": "slide-right"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "DEFINING THE ESCAPE",
          "kicker": "Architecture is not just walls and windows; it is the framing of a life. We capture the raw beauty o",
          "accent": "#004d40",
          "transition": "flip"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "ELEMENTAL INTEGRATION",
          "kicker": "The perfect blend of natural wood, industrial fireplace, and deep teal accents. Structure meets sere",
          "accent": "#8d6e63",
          "transition": "slide-left"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "MINIMALISM AS POWER",
          "kicker": "Less is more. By stripping away the excess, we reveal the pure, powerful geometry of the space and t",
          "accent": "#004d40",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "THE ULTIMATE SCALE",
          "kicker": "Mastering the dramatic archway. Our designs are built to withstand time, creating monumental, lastin",
          "accent": "#6d4c41",
          "transition": "slide-top"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "GEOMETRY AND LIGHT",
          "kicker": "The interplay of light and negative space defines the mood. Every angle is calculated for maximum im",
          "accent": "#795548",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "THE DETAIL MATTERS",
          "kicker": "From the hearth to the window frame, every detail is a testament to uncompromising quality and struc",
          "accent": "#004d40",
          "transition": "flip"
        },
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "BUILDING YOUR LEGACY",
          "kicker": "Your vision, realized. We don't just design rooms; we engineer the backdrop for a life of enduring l",
          "accent": "#d4c8c3",
          "transition": "slide-left"
        }
      ]}
    />
  );
};
