import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheGeometryofScale: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      sceneLengthInFrames={280}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/14b6cd20d8.png",
          "caption": "WHERE STRUCTURE MEETS THE WILD.",
          "kicker": "the architecture is merely a frame for the raw, uncompromising power of the mountain range beyond.",
          "accent": "#A9A9A9",
          "transition": "fade"
        },
        {
          "src": "uploads/9dc402e750.png",
          "caption": "A VIEW OF IMMENSE DEPTH.",
          "kicker": "the weight of the landscape settles into the quiet, sophisticated geometry of the space.",
          "accent": "#5D7A8C",
          "transition": "slide-right"
        },
        {
          "src": "uploads/e815ac291e.png",
          "caption": "THE COLD BEAUTY OF THE PEAK.",
          "kicker": "a stark, crystalline dialogue between man's comfort and nature's unforgiving, beautiful scale.",
          "accent": "#A0B2B8",
          "transition": "flip"
        },
        {
          "src": "uploads/35244de977.png",
          "caption": "THE CURVE OF THE HORIZON.",
          "kicker": "it is here that the boundary dissolves—a breathtaking, overwhelming geometry of stone and sky.",
          "accent": "#4a698a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/9467c4fe76.png",
          "caption": "THE QUIET AFTER THE STORM.",
          "kicker": "finding the necessary stillness within the overwhelming, enduring presence of the earth.",
          "accent": "#5d6d7e",
          "transition": "fade"
        }
      ]}
    />
  );
};
