import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const THEPLASTICMANIFESTO: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"film"}
      sceneLengthInFrames={78}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "POV: THE VIBE IS OFF",
          "kicker": "you thought it was just a bad day. it's a systemic failure.",
          "accent": "#ff3d3d",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "YOU CAN'T IGNORE THIS.",
          "kicker": "the silent rage of the modern era. it's palpable.",
          "accent": "#ff8a2a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE UNFILTERED TRUTH.",
          "kicker": "they said we needed to smile. they were wrong.",
          "accent": "#a78bfa",
          "transition": "flip"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THIS IS THE WARNING.",
          "kicker": "the moment the facade cracks. the smoke is rising.",
          "accent": "#ff3d3d",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE ENERGY SHIFT.",
          "kicker": "when the patience runs out, the performance begins.",
          "accent": "#ff8a2a",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "DON'T ASK QUESTIONS.",
          "kicker": "just watch the fallout. the reckoning is here.",
          "accent": "#ff3d3d",
          "transition": "slide-right"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLOW UP IS RAGE.",
          "kicker": "it's not about the look. it's about the sheer, unadulterated spite.",
          "accent": "#ff3d3d",
          "transition": "slide-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE MAIN CHARACTER ENERGY.",
          "kicker": "you finally realized you don't have to perform for anyone.",
          "accent": "#a78bfa",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE ANTI-AESTHETIC.",
          "kicker": "raw, unfiltered, and completely unbothered by your opinion.",
          "accent": "#ff8a2a",
          "transition": "wipe-bottom"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THIS IS THE MOOD BOARD.",
          "kicker": "a perfect blend of existential dread and cheap cigarettes.",
          "accent": "#ffd43a",
          "transition": "slide-top"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THE REALITY CHECK.",
          "kicker": "it's not a phase. it's the permanent state of being over it all.",
          "accent": "#ff3d3d",
          "transition": "wipe-right"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "SAVE THIS FOR LATER.",
          "kicker": "a reminder that sometimes, the best response is just smoke.",
          "accent": "#ff8a2a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE FINAL FORM.",
          "kicker": "you can't stop the inevitable. the smoke always rises.",
          "accent": "#ff3d3d",
          "transition": "fade"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "NO APOLOGIES.",
          "kicker": "we are the glitch in the matrix. the beautiful, angry glitch.",
          "accent": "#ff3d3d",
          "transition": "wipe"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE PAYOFF.",
          "kicker": "the beat drops, the smoke clears, and the message remains.",
          "accent": "#ff3d3d",
          "transition": "flip"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "FEEL THE HEAT.",
          "kicker": "this is the visceral, cinematic scream of the plastic doll.",
          "accent": "#ff8a2a",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE VIBE IS IMMORTAL.",
          "kicker": "don't just scroll past this. absorb the energy.",
          "accent": "#a78bfa",
          "transition": "slide-right"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "IT'S A MOVEMENT.",
          "kicker": "the collective sigh of the burnt-out, beautiful generation.",
          "accent": "#ffd43a",
          "transition": "clock-wipe"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "THE ENDING SHOT.",
          "kicker": "remember this feeling. remember the smoke. remember the rage.",
          "accent": "#ff3d3d",
          "transition": "wipe-bottom"
        }
      ]}
    />
  );
};
