import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheRoastSession: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-archivo-black), system-ui, sans-serif"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"minimal"}
      sceneLengthInFrames={94}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "WHO ARE YOU LOOKING AT?",
          "kicker": "the curtain is always falling, but the spotlight is on you.",
          "accent": "#ff0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE VIBE CHECK FAILED.",
          "kicker": "you thought you were slick, but we saw the whole thing.",
          "accent": "#d35400",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "TOO MUCH CONFIDENCE.",
          "kicker": "you don't need to try this hard. just be.",
          "accent": "#b88600",
          "transition": "flip"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "BRIGHT. LOUD. UNSTOPPABLE.",
          "kicker": "we came to roast, and we brought the whole damn circus.",
          "accent": "#ff69b4",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "SINISTER. ALWAYS SINISTER.",
          "kicker": "the clown knows all your secrets. and he's laughing.",
          "accent": "#d82020",
          "transition": "wipe"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "THE GRIT. THE EDGE.",
          "kicker": "this is what happens when the lights go down and the truth comes out.",
          "accent": "#cc4422",
          "transition": "slide-top"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "DID YOU HEAR THAT?",
          "kicker": "the silence was the loudest part. we heard it all.",
          "accent": "#333333",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE DRAMATIC PAUSE.",
          "kicker": "before the punchline. before the final, devastating look.",
          "accent": "#5c2d2d",
          "transition": "fade"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "YOU THINK YOU'RE SAFE?",
          "kicker": "the smoke clears, but the damage remains. always.",
          "accent": "#34495e",
          "transition": "flip"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE FINAL WARNING.",
          "kicker": "don't mistake our chill for weakness. we're lethal.",
          "accent": "#4682b4",
          "transition": "slide-right"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "TOO MUCH ENERGY.",
          "kicker": "you brought the glitter, we brought the scorched earth.",
          "accent": "#0077cc",
          "transition": "wipe"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "THE UNSEEN TRUTH.",
          "kicker": "the smile never reaches the eyes. you know it.",
          "accent": "#1a1a1a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "NO MERCY. NO FILTER.",
          "kicker": "we don't participate in the drama. we *are* the drama.",
          "accent": "#a0a0a0",
          "transition": "slide-top"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE GAZE. THE JUDGMENT.",
          "kicker": "you can't look away. you know the score.",
          "accent": "#b8a08c",
          "transition": "fade"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE EXIT. THE PAYOFF.",
          "kicker": "we leave you breathless, laughing, and slightly exposed.",
          "accent": "#a08c7e",
          "transition": "flip"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "REMEMBER THIS FEELING.",
          "kicker": "the moment the air changes. the moment you realize who runs the show.",
          "accent": "#222222",
          "transition": "slide-bottom"
        }
      ]}
    />
  );
};
