import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const TheRoastReel: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"minimal"}
      sceneLengthInFrames={205}
      transitionLengthInFrames={18}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "SMOKE. AND SILENCE.",
          "kicker": "you thought you were ready for this? think again.",
          "accent": "#333333"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "BRIGHT. AND UNFILTERED.",
          "kicker": "the vibe is immaculate, and the roast is lethal.",
          "accent": "#ff69b4",
          "transition": "wipe"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "NO MERCY. JUST TRUTH.",
          "kicker": "we don't whisper shade, we broadcast it.",
          "accent": "#cc4c22",
          "transition": "flip"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "REBEL. AGAINST THE NARRATIVE.",
          "kicker": "this is the moment you realize you're not the main character.",
          "accent": "#006666",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "GRIT. AND GOLD.",
          "kicker": "keeping it low key, but the burn is high definition.",
          "accent": "#d45000",
          "transition": "slide-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE FINAL WORD.",
          "kicker": "you came for the drama, but you stayed for the roast.",
          "accent": "#a0522d",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "CINEMATIC. AND UNBOTHERED.",
          "kicker": "the perfect exit. leave them talking.",
          "accent": "#a08c74",
          "transition": "fade"
        }
      ]}
    />
  );
};
