import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const UNBOTHERED: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-dm-mono), monospace"}
      kickerFontFamily={"var(--font-dm-mono), monospace"}
      decorStyle={"minimal"}
      sceneLengthInFrames={113}
      transitionLengthInFrames={12}
      scenes={[
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE VIBE IS IMMACULATE.",
          "kicker": "they don't even know they're watching a masterclass in indifference. just glide.",
          "accent": "#A0522D",
          "transition": "wipe"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "NO FILTER. NO APOLOGIES.",
          "kicker": "this is the raw, unfiltered energy of knowing your worth. don't try to keep up.",
          "accent": "#ff69b4",
          "transition": "flip"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "TOO COOL TO CARE.",
          "kicker": "the kind of effortless swagger that makes everyone else look like they're trying too hard.",
          "accent": "#333333",
          "transition": "slide-right"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE CONFIDENCE IS A WEAPON.",
          "kicker": "they thought they were funny, but we're operating on a different plane of existence. watch us.",
          "accent": "#ffb72a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/91933ae417.png",
          "caption": "SINISTER GRACE.",
          "kicker": "the look you give them when they make a questionable life choice. we see you. we judge you.",
          "accent": "#cc0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/e50acb0870.png",
          "caption": "PURE INTENSITY.",
          "kicker": "this isn't a moment, it's a permanent state of being. grit and smoke and zero regrets.",
          "accent": "#cc4422",
          "transition": "slide-top"
        },
        {
          "src": "uploads/7dfcbe29b3.png",
          "caption": "THE STARE DOWN.",
          "kicker": "direct eye contact is the ultimate roast. you can't look away. we own this frame.",
          "accent": "#008080",
          "transition": "slide-bottom"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "MYSTERY MODE: ACTIVATED.",
          "kicker": "the kind of cool that doesn't need to speak. just the subtle tilt of the head and the smoke.",
          "accent": "#a08060",
          "transition": "fade"
        },
        {
          "src": "uploads/6f25c54707.png",
          "caption": "THE GLOW UP IS REAL.",
          "kicker": "we don't try to fit in, we set the standard. the drama is always worth the smoke.",
          "accent": "#ffffff",
          "transition": "flip"
        },
        {
          "src": "uploads/7b9b0c268b.png",
          "caption": "UNBOTHERED VIBES ONLY.",
          "kicker": "they thought the spotlight was for them. we just showed up and took it. the energy shift is palpable",
          "accent": "#ff69b4",
          "transition": "slide-right"
        },
        {
          "src": "uploads/5afe1ee1ce.png",
          "caption": "THE ANTI-CLIMAX.",
          "kicker": "the best roasts are the ones that require zero effort. just existing is the punchline.",
          "accent": "#333333",
          "transition": "slide-left"
        },
        {
          "src": "uploads/dd0971620d.png",
          "caption": "THE FINAL WORD.",
          "kicker": "when the roast is so good, you don't even have to yell it. just let the smoke do the talking.",
          "accent": "#8B0000",
          "transition": "wipe"
        },
        {
          "src": "uploads/84607d8987.png",
          "caption": "THE EXIT.",
          "kicker": "the perfect fade out. leaving them wondering what just happened. cinematic.",
          "accent": "#cccccc",
          "transition": "fade"
        }
      ]}
    />
  );
};
