import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const UrbanDrift: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      scenes={[
        {
          "src": "uploads/d0385e3b5b.png",
          "caption": "MOTION",
          "kicker": "chasing the light",
          "accent": "#ff3d3d",
          "transition": "fade"
        },
        {
          "src": "uploads/913197aeec.png",
          "caption": "GOLDEN HOUR",
          "kicker": "where the day meets the night",
          "accent": "#ffd43a",
          "transition": "slide-right"
        },
        {
          "src": "uploads/eae75e9aa5.png",
          "caption": "ESCAPE",
          "kicker": "drifting into the blue",
          "accent": "#4cc9ff",
          "transition": "flip"
        },
        {
          "src": "uploads/2bbf83280c.png",
          "caption": "POWER",
          "kicker": "raw energy unleashed",
          "accent": "#ff8a2a",
          "transition": "slide-left"
        },
        {
          "src": "uploads/cc49cef394.png",
          "caption": "MYSTERY",
          "kicker": "secrets in the shadows",
          "accent": "#a78bfa",
          "transition": "wipe"
        }
      ]}
    />
  );
};
