import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const WildPassage: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-playfair), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"film"}
      theme={"editorial"}
      motionFeel={"snappy"}
      transitionEnergy={"medium"}
      gradePreset={"neutral_punch"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/93f20b5b1d.png",
          "caption": "THE BEAR'S QUIET PASSAGE",
          "kicker": "a moment of wild, undisturbed movement",
          "accent": "#8c949c",
          "transition": "fade",
          "narration": "Watch the bear move across the meadow, a truly wild and serene moment.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/2096c202a2.png",
          "caption": "DEEP IN THE FOLIAGE",
          "kicker": "a watchful presence emerges from the green",
          "accent": "#6b8e23",
          "transition": "slide-left",
          "narration": "The bear pauses, surrounded by dense, watchful green foliage.",
          "textPlacement": "top-left"
        },
        {
          "src": "uploads/020b874f25.png",
          "caption": "MOUNTAIN GUARDIAN",
          "kicker": "the panther surveys the vast, rugged peaks",
          "accent": "#8a9a8a",
          "transition": "flip",
          "narration": "The panther surveys the massive, rugged peaks from the foreground.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/cc4e7cd32b.png",
          "caption": "BLACK PANTHER POSITIONED FOREGROUND",
          "kicker": "nothing is missed in that stare",
          "accent": "#708090",
          "transition": "slide-right",
          "narration": "It locks eyes with the camera, an intense and unbroken stare across the mountains.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/9f23ef5d69.png",
          "caption": "UNFLINCHING PORTRAIT",
          "kicker": "the wild gaze, unedited",
          "accent": "#555555",
          "transition": "wipe",
          "narration": "The panther holds the frame, an unedited, powerful portrait against the landscape.",
          "textPlacement": "bottom-left"
        },
        {
          "src": "uploads/f582a0440d.png",
          "caption": "STEALTH IN THE GRASS",
          "kicker": "moving through the untamed edge",
          "accent": "#777777",
          "transition": "slide-top",
          "narration": "It moves with incredible stealth, partially hidden in the tall, dry grass.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/88de89ba18.png",
          "caption": "LOW TO THE GROUND",
          "kicker": "a coiled, watchful intensity",
          "accent": "#555555",
          "transition": "slide-bottom",
          "narration": "The animal drops low, a coiled intensity visible just above the ground.",
          "textPlacement": "top-center"
        },
        {
          "src": "uploads/0d3fbc9cfc.png",
          "caption": "EMERGING MAJESTY",
          "kicker": "the final reveal over the valley",
          "accent": "#8c9a9e",
          "transition": "wipe-right",
          "narration": "Finally, it emerges in full majesty, overlooking the entire valley below.",
          "textPlacement": "top-center"
        }
      ]}
      sceneTTSPaths={["tts/WildPassage-scene-0.wav","tts/WildPassage-scene-1.wav","tts/WildPassage-scene-2.wav","tts/WildPassage-scene-3.wav","tts/WildPassage-scene-4.wav","tts/WildPassage-scene-5.wav","tts/WildPassage-scene-6.wav","tts/WildPassage-scene-7.wav"]}
    />
  );
};
