import React from "react";
import { CinematicReel } from "../components/CinematicReel";

// Auto-generated by /api/agent. Do not edit by hand — re-run the agent instead.
export const WildApex: React.FC = () => {
  return (
    <CinematicReel
      brandName={"VISIO●REEL"}
      captionFontFamily={"var(--font-playfair), Georgia, serif"}
      kickerFontFamily={"var(--font-dm-sans), system-ui, sans-serif"}
      decorStyle={"minimal"}
      theme={"editorial"}
      motionFeel={"smooth"}
      transitionEnergy={"medium"}
      gradePreset={"neutral_punch"}
      sceneLengthInFrames={173}
      transitionLengthInFrames={8}
      scenes={[
        {
          "src": "uploads/93f20b5b1d.png",
          "caption": "BEAR CROSSES THE MEADOW",
          "kicker": "a black bear crosses the hillside, unconcerned.",
          "accent": "#a8b39c",
          "transition": "wipe-right",
          "narration": "The first sign of movement in the meadow. A black bear crosses the hillside, unconcerned."
        },
        {
          "src": "uploads/2096c202a2.png",
          "caption": "WATCHFUL. PRIMAL. UNSEEN.",
          "kicker": "the bear pauses, framed by dense, wet foliage.",
          "accent": "#7f9e8c",
          "transition": "flip",
          "narration": "Watchful. Primal. Unseen. The bear pauses, framed by dense, wet foliage."
        },
        {
          "src": "uploads/020b874f25.png",
          "caption": "SHADOWS MOVE THROUGH VALLEY",
          "kicker": "the panther traverses the grassy slope, a silent hunter.",
          "accent": "#6b7b5e",
          "transition": "slide-left",
          "narration": "Shadows move through the valley floor. The panther traverses the grassy slope, a silent hunter."
        },
        {
          "src": "uploads/cc4e7cd32b.png",
          "caption": "MAJESTY IN THE OPEN LANDSCAPE",
          "kicker": "the panther holds its ground, surveying the vast forest.",
          "accent": "#5a634d",
          "transition": "slide-right",
          "narration": "Majesty in the open landscape. The panther holds its ground, surveying the vast forest."
        },
        {
          "src": "uploads/9f23ef5d69.png",
          "caption": "DIRECT GAZE. NO FILTER.",
          "kicker": "the black panther fills the frame, intense and immediate.",
          "accent": "#000000",
          "transition": "fade",
          "narration": "Direct gaze. No filter. The black panther fills the frame, intense and immediate."
        },
        {
          "src": "uploads/f582a0440d.png",
          "caption": "STEALTH IS A LANGUAGE",
          "kicker": "observing from the cover of the tall, dry grass.",
          "accent": "#8c8c8c",
          "transition": "wipe-bottom",
          "narration": "Stealth is a language. Observing from the cover of the tall, dry grass."
        },
        {
          "src": "uploads/88de89ba18.png",
          "caption": "PROXIMITY OF THE WILD",
          "kicker": "a close encounter, the subject dominates the foreground.",
          "accent": "#555555",
          "transition": "clock-wipe",
          "narration": "The proximity of the wild. A close encounter, the subject dominates the foreground."
        },
        {
          "src": "uploads/0d3fbc9cfc.png",
          "caption": "EMERGENCE FROM THE DEEP GREEN",
          "kicker": "the panther steps into the light, surveying the expanse.",
          "accent": "#8c9a9e",
          "transition": "iris",
          "narration": "Emergence from the deep green. The panther steps into the light, surveying the expanse."
        }
      ]}
      sceneTTSPaths={["tts/WildApex-scene-0.wav","tts/WildApex-scene-1.wav","tts/WildApex-scene-2.wav","tts/WildApex-scene-3.wav","tts/WildApex-scene-4.wav","tts/WildApex-scene-5.wav","tts/WildApex-scene-6.wav","tts/WildApex-scene-7.wav"]}
    />
  );
};
